repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: forbid-new-submodules
-   repo: https://github.com/igankevich/pre-commit-cpp
    rev: 0.6.6
    hooks:
    -   id: normalise
        types: [text]
        files: .*
        additional_dependencies: ['chardet']
    -   id: normalise-cpp
        files: (^src/[^\.]+|\.cc)$
    -   id: header-guard
        files: ^src/[^\.]+$
    -   id: legal
        files: (^src/[^\.]+|\.cc|config\.in)$
        args: ['--copyright-string=©', '--programme-name=UNISTDX',
               '--license-notice=unlicense',
               '--preamble=UNISTDX — C++ library for Linux system calls.']
