UNISTDX: sys::byte_buffer Class Reference
sys::byte_buffer Class Reference
C++ concepts » Containers
Byte buffer which uses direct memory allocation for maximum performance.
Public Types
typedef char value_type
Alias to char.
typedef value_type * iterator
Pointer to char.
typedef const value_type * const_iterator
Constant pointer to char.
typedef std::size_t size_type
Alias to std::size_t.
Public Member Functions
byte_buffer (const byte_buffer &)=delete
byte_buffer & operator= (const byte_buffer &)=delete
byte_buffer (byte_buffer &&rhs)
Move-constructor.
byte_buffer (size_type size)
Construct byte buffer with size size.
iterator data () noexcept
Get pointer to raw data.
const_iterator data () const noexcept
Get pointer to raw data.
iterator begin () noexcept
Get iterator to the beginning of the container.
const_iterator begin () const noexcept
Get iterator to the beginning of the container.
iterator end () noexcept
Get iterator to the end of the container.
const_iterator end () const noexcept
Get iterator to the end of the container.
size_type size () const noexcept
Get number of bytes in byte buffer.
operator bool () const noexcept
Check if the buffer is valid.
bool operator! () const noexcept
Check if the buffer is valid.
void resize (size_type new_size)
Resize the buffer preserving its contents.
void grow ()
Double the buffer size.
void swap (byte_buffer &rhs) noexcept
Swap with rhs.
Static Public Member Functions
static size_type max_size () noexcept
Returns maximum size a buffer may occupy (theoretical limit).
Detailed Description
Byte buffer which uses direct memory allocation for maximum performance.
Date
2018-05-21
Author
Ivan Gankevich
See also
mmap(2)
mremap(2)
madvise(2)
Uses mmap(2) and system calls to bypass memory allocators.
Uses mremap(2) to efficiently resize the buffer without copying.
Uses madvise(2) to optimise for sequential access and prevent core dumping.
Definition at line 25 of file byte_buffer.
Constructor & Destructor Documentation
byte_buffer()
sys::byte_buffer::byte_buffer (size_type size) explicit
Construct byte buffer with size size.
Exceptions
bad_call
See also
mmap(2)
madvise(2)
Definition at line 25 of file byte_buffer.cc.
References size(), and UNISTDX_CHECK2.
Member Function Documentation
grow()
void sys::byte_buffer::grow () inline
Double the buffer size.
Exceptions
std::length_error when maximum size is reached.
bad_call when system error occurs
See also
mremap(2)
madvise(2)
Definition at line 140 of file byte_buffer.
References max_size(), and resize().
resize()
void sys::byte_buffer::resize (size_type new_size)
Resize the buffer preserving its contents.
Exceptions
bad_call
See also
mremap(2)
madvise(2)
Definition at line 55 of file byte_buffer.cc.
References UNISTDX_CHECK2.
Referenced by grow().