UNISTDX: sys::basic_bstream< Ch, Tr, Size > Class Template Reference
sys::basic_bstream< Ch, Tr, Size > Class Template Reference
C++ concepts » StreamsSystem abstractions » | Network
Input/output stream that reads/writes everything in binary format with network byte order.
Public Types
typedef Ch char_type
Character type.
typedef Tr traits_type
Character traits type.
typedef Size size_type
Size type (defaults to 4-byte integer).
typedef std::basic_streambuf< Ch, Tr > streambuf_type
Stream buffer type.
typedef std::basic_string< Ch, Tr > string_type
String type used for input and output.
Public Member Functions
basic_bstream (streambuf_type *buf)
Construct binary stream for stream buffer buf.
basic_bstream (basic_bstream &&rhs)
Move-constructor.
basic_bstream (const basic_bstream &)=delete
basic_bstream & operator= (const basic_bstream &)=delete
basic_bstream & operator= (basic_bstream &&)=delete
streambuf_type * rdbuf () noexcept
Get stream buffer.
const streambuf_type * rdbuf () const noexcept
Get stream buffer.
streambuf_type * rdbuf (streambuf_type *rhs)
Set stream buffer to rhs.
void sync ()
Synchronise both input and output buffers.
void flush ()
Synchronise both input and output buffers.
basic_bstream & operator<< (bool rhs)
Insert operator for standard type.
basic_bstream & operator>> (bool &rhs)
Get operator for standard type.
template<class T >
basic_bstream & operator<< (const sys::bytes< T, Ch > &rhs)
Insert operator for bytes.
template<class T >
basic_bstream & operator>> (sys::bytes< T, Ch > &rhs)
Get operator for bytes.
basic_bstream & write (const char_type *buf, std::streamsize n)
basic_bstream & read (char_type *buf, std::streamsize n)
basic_bstream & operator<< (char rhs)
basic_bstream & operator>> (char &rhs)
basic_bstream & operator<< (i8 rhs)
basic_bstream & operator>> (i8 &rhs)
basic_bstream & operator<< (i16 rhs)
basic_bstream & operator>> (i16 &rhs)
basic_bstream & operator<< (i32 rhs)
basic_bstream & operator>> (i32 &rhs)
basic_bstream & operator<< (i64 rhs)
basic_bstream & operator>> (i64 &rhs)
basic_bstream & operator<< (u8 rhs)
basic_bstream & operator>> (u8 &rhs)
basic_bstream & operator<< (u16 rhs)
basic_bstream & operator>> (u16 &rhs)
basic_bstream & operator<< (u32 rhs)
basic_bstream & operator>> (u32 &rhs)
basic_bstream & operator<< (u64 rhs)
basic_bstream & operator>> (u64 &rhs)
basic_bstream & operator<< (f32 rhs)
basic_bstream & operator>> (f32 &rhs)
basic_bstream & operator<< (f64 rhs)
basic_bstream & operator>> (f64 &rhs)
basic_bstream & operator<< (f128 rhs)
basic_bstream & operator>> (f128 &rhs)
basic_bstream & operator<< (string_type rhs)
basic_bstream & operator>> (string_type &rhs)
Detailed Description
template<class Ch, class Tr = std::char_traits<Ch>, class Size = u32>
class sys::basic_bstream< Ch, Tr, Size >
Input/output stream that reads/writes everything in binary format with network byte order.
Date
2018-04-20
Author
Ivan Gankevich
Template Parameters
Ch character type
Tr character traits type
Size size type (defaults to 4-byte integer)
Definition at line 38 of file bstream.
Member Function Documentation
read()
template<class Ch , class Tr = std::char_traits<Ch>, class Size = u32> basic_bstream& sys::basic_bstream< Ch, Tr, Size >::read (char_type * buf, std::streamsize n) inline
Get n bytes from binary stream and store them in byte buffer pointed by buf.
Definition at line 184 of file bstream.
References std::basic_streambuf::sgetn().
Referenced by sys::basic_bstream< Ch, Tr, Size >::operator>>().
write()
template<class Ch , class Tr = std::char_traits<Ch>, class Size = u32> basic_bstream& sys::basic_bstream< Ch, Tr, Size >::write (const char_type * buf, std::streamsize n) inline
Put n bytes from byte buffer pointed by buf to binary stream.
Definition at line 172 of file bstream.
References std::basic_streambuf::sputn().
Referenced by sys::basic_bstream< Ch, Tr, Size >::operator<<().