UNISTDX: sys::event_poller Class Reference
sys::event_poller Class Reference
C++ concepts » SemaphoresC++ concepts » | ContainersSystem abstractions » | IO
File descriptor poller.
Public Types
typedef container_type::value_type value_type
Container element type.
typedef value_type * iterator
Container iterator type.
typedef const value_type * const_iterator
Container const iterator type.
Public Member Functions
event_poller (int maxevents=4096/sizeof(epoll_event))
Construct event poller with maxevent number of events.
fd_type pipe_in () const noexcept
void notify_one () noexcept
void notify_all () noexcept
const_iterator begin () const noexcept
Returns iterator to the beginning of array of events.
const_iterator end () const noexcept
Returns iterator to the end of array of events.
void emplace (fd_type fd, event ev)
Construct epoll_event in-place with file descriptor fd and event mask ev and add it to the poller.
void insert (const epoll_event &ev)
Add file descriptor-event mask pair to the poller.
void replace (const epoll_event &ev)
Update event mask for existing file descriptor.
void erase (fd_type fd)
Remove file descriptor fd from the poller.
void erase (const epoll_event &ev)
Remove file descriptor-event mask pair to the poller.
void resize (int new_size)
template<class Lock >
void wait (Lock &lock)
template<class Lock , class Pred >
void wait (Lock &lock, Pred pred)
Wait for events to occur unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Rep , class Period >
std::cv_status wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur)
Wait for events to occur specified amount of time dur unlocking lock for the duration of the wait.
template<class Lock , class Rep , class Period , class Pred >
bool wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur, Pred pred)
Wait for events to occur specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
template<class Lock , class Duration >
std::cv_status wait_until (Lock &lock, const time_point< Duration > &tp)
Wait for events to occur until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Duration , class Pred >
bool wait_until (Lock &lock, const time_point< Duration > &tp, Pred pred)
Wait for events to occur until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Clock , class Duration >
std::cv_status wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp)
Wait for events to occur until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Clock , class Duration , class Pred >
bool wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp, Pred pred)
Wait for events to occur until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Detailed Description
File descriptor poller.
Date
2018-05-21
Author
Ivan Gankevich
File descriptor poller implemented with epoll_create1(2) system call having condition variable-like interface.
The poller has condition variable interface for waiting and notifying.
Definition at line 31 of file poller.
Constructor & Destructor Documentation
event_poller()
sys::event_poller::event_poller (int maxevents = 4096/sizeof(epoll_event)) inline explicit
Construct event poller with maxevent number of events.
Exceptions
bad_call
See also
epoll_ctl(2)
epoll_create1(2)
Definition at line 65 of file poller.
References pipe_in().
Member Function Documentation
emplace()
void sys::event_poller::emplace (fd_type fd, event ev) inline
Construct epoll_event in-place with file descriptor fd and event mask ev and add it to the poller.
Exceptions
bad_call
See also
epoll_ctl(2)
Definition at line 124 of file poller.
erase() [1/2]
void sys::event_poller::erase (fd_type fd) inline
Remove file descriptor fd from the poller.
Exceptions
bad_call
See also
epoll_ctl(2)
Definition at line 153 of file poller.
erase() [2/2]
void sys::event_poller::erase (const epoll_event & ev) inline
Remove file descriptor-event mask pair to the poller.
Exceptions
bad_call
See also
epoll_ctl(2)
Equivalent to erase(ev.fd()).
Definition at line 165 of file poller.
References sys::epoll_event::fd().
insert()
void sys::event_poller::insert (const epoll_event & ev) inline
Add file descriptor-event mask pair to the poller.
Exceptions
bad_call
See also
epoll_ctl(2)
Definition at line 134 of file poller.
notify_all()
void sys::event_poller::notify_all () inline noexcept
Notify poller of an external event via pipe_in.
Definition at line 99 of file poller.
References notify_one().
notify_one()
void sys::event_poller::notify_one () inline noexcept
Notify poller of an external event via pipe_in.
Definition at line 89 of file poller.
References sys::pipe::out(), and sys::fildes::write().
Referenced by notify_all().
pipe_in()
fd_type sys::event_poller::pipe_in () const inline noexcept
Returns file descriptor which is used to notify poller of an external event.
Definition at line 81 of file poller.
References sys::fildes::fd(), and sys::pipe::in().
Referenced by event_poller().
replace()
void sys::event_poller::replace (const epoll_event & ev) inline
Update event mask for existing file descriptor.
See also
epoll_ctl(2)
Definition at line 143 of file poller.
resize()
void sys::event_poller::resize (int new_size) inline
Change maximum number of events that the poller handles at a time
Definition at line 173 of file poller.
References std::vector::resize().
wait() [1/2]
template<class Lock > void sys::event_poller::wait (Lock & lock) inline
Wait for events to occur unlocking lock for the duration of the wait.
Definition at line 183 of file poller.
wait() [2/2]
template<class Lock , class Pred > void sys::event_poller::wait (Lock & lock, Pred pred) inline
Wait for events to occur unlocking lock for the duration of the wait until predicate pred becomes true.
Exceptions
bad_call if system error occurs, except std::errc::interrupted
See also
epoll_wait(2)
std::errc
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 202 of file poller.
wait_for() [1/2]
template<class Lock , class Rep , class Period > std::cv_status sys::event_poller::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur) inline
Wait for events to occur specified amount of time dur unlocking lock for the duration of the wait.
Exceptions
bad_call if system error occurs, except std::errc::interrupted
See also
epoll_wait(2)
std::errc
Definition at line 220 of file poller.
References std::chrono::duration_cast().
Referenced by wait_for(), and wait_until().
wait_for() [2/2]
template<class Lock , class Rep , class Period , class Pred > bool sys::event_poller::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur, Pred pred) inline
Wait for events to occur specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 241 of file poller.
References wait_for().
wait_until() [1/2]
template<class Lock , class Duration , class Pred > bool sys::event_poller::wait_until (Lock & lock, const time_point< Duration > & tp, Pred pred) inline
Wait for events to occur until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
Returns
predicate value
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 285 of file poller.
References std::max(), std::chrono::steady_clock::now(), and wait_for().
wait_until() [2/2]
template<class Lock , class Clock , class Duration , class Pred > bool sys::event_poller::wait_until (Lock & lock, const std::chrono::time_point< Clock, Duration > & tp, Pred pred) inline
Wait for events to occur until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 320 of file poller.
References std::chrono::steady_clock::now(), and wait_until().