UNISTDX: sys::posix_semaphore Class Reference
sys::posix_semaphore Class Reference
System abstractions » ProcessesC++ concepts » | Semaphores
Semaphore, implemented using POSIX system calls.
Public Types
typedef std::chrono::system_clock clock_type
Clock type used in this class.
Public Member Functions
posix_semaphore (semaphore_type type)
Construct semaphore with specified type.
void wait ()
Wait until other process/thread calls sysv_semaphore::notify_one or sysv_semaphore::notify_all on this semaphore.
template<class Lock >
void wait (Lock &lock)
Wait on the semaphore unlocking lock for the duration of the wait.
template<class Lock , class Pred >
void wait (Lock &lock, Pred pred)
Wait on the semaphore unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Rep , class Period >
std::cv_status wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur)
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait.
template<class Lock , class Rep , class Period , class Pred >
bool wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur, Pred pred)
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
template<class Lock , class Duration >
std::cv_status wait_until (Lock &lock, const std::chrono::time_point< clock_type, Duration > &tp)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Duration , class Pred >
bool wait_until (Lock &lock, const std::chrono::time_point< clock_type, Duration > &tp, Pred pred)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Clock , class Duration >
std::cv_status wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Clock , class Duration , class Pred >
bool wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp, Pred pred)
Wait on the semaphore until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
void notify_one ()
Notify one process that wait on this semaphore.
void notify_all ()
Notify all processes that wait on this semaphore.
void notify_all (int n)
Notify n processes that wait on this semaphore.
Detailed Description
Semaphore, implemented using POSIX system calls.
Date
2018-05-21
Author
Ivan Gankevich
Suitable for both processes and threads.
Definition at line 356 of file semaphore.
Constructor & Destructor Documentation
posix_semaphore()
sys::posix_semaphore::posix_semaphore (semaphore_type type) inline explicit
Construct semaphore with specified type.
Exceptions
bad_call
Definition at line 371 of file semaphore.
Member Function Documentation
notify_all() [1/2]
void sys::posix_semaphore::notify_all () inline
Notify all processes that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 516 of file semaphore.
References sys::sysv_semaphore::notify_all().
notify_all() [2/2]
void sys::posix_semaphore::notify_all (int n) inline
Notify n processes that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 522 of file semaphore.
References sys::sysv_semaphore::notify_one().
notify_one()
void sys::posix_semaphore::notify_one () inline
Notify one process that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 510 of file semaphore.
References UNISTDX_CHECK.
Referenced by sys::basic_shmembuf< Ch, Tr >::basic_shmembuf(), and sys::basic_shmembuf< Ch, Tr >::unlock().
wait() [1/3]
void sys::posix_semaphore::wait () inline
Wait until other process/thread calls sysv_semaphore::notify_one or sysv_semaphore::notify_all on this semaphore.
Exceptions
bad_call
See also
semop(2)
sem_wait(2)
Definition at line 385 of file semaphore.
References UNISTDX_CHECK.
Referenced by sys::basic_shmembuf< Ch, Tr >::lock().
wait() [2/3]
template<class Lock > void sys::posix_semaphore::wait (Lock & lock) inline
Wait on the semaphore unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semop(2)
sem_wait(2)
Definition at line 394 of file semaphore.
References sys::sysv_semaphore::wait().
wait() [3/3]
template<class Lock , class Pred > void sys::posix_semaphore::wait (Lock & lock, Pred pred) inline
Wait on the semaphore unlocking lock for the duration of the wait until predicate pred becomes true.
Exceptions
bad_call
See also
semop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
See also
sem_wait(2)
Definition at line 404 of file semaphore.
References sys::sysv_semaphore::wait().
wait_for() [1/2]
template<class Lock , class Rep , class Period > std::cv_status sys::posix_semaphore::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur) inline
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semtimedop(2)
sem_timedwait(2)
Definition at line 417 of file semaphore.
References std::chrono::system_clock::now(), and sys::sysv_semaphore::wait_until().
wait_for() [2/2]
template<class Lock , class Rep , class Period , class Pred > bool sys::posix_semaphore::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur, Pred pred) inline
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
Exceptions
bad_call
See also
semtimedop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
See also
sem_timedwait(2)
Definition at line 427 of file semaphore.
References std::chrono::system_clock::now(), and sys::sysv_semaphore::wait_until().
wait_until() [1/4]
template<class Lock , class Duration > std::cv_status sys::posix_semaphore::wait_until (Lock & lock, const std::chrono::time_point< clock_type, Duration > & tp) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
sem_timedwait(2)
Definition at line 440 of file semaphore.
References std::chrono::nanoseconds::count(), std::chrono::duration_cast(), std::chrono::time_point_cast(), and UNISTDX_THROW_BAD_CALL.
wait_until() [2/4]
template<class Lock , class Duration , class Pred > bool sys::posix_semaphore::wait_until (Lock & lock, const std::chrono::time_point< clock_type, Duration > & tp, Pred pred) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
Returns
predicate value
Exceptions
bad_call
See also
sem_timedwait(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 473 of file semaphore.
References sys::sysv_semaphore::wait_until().
wait_until() [3/4]
template<class Lock , class Clock , class Duration > std::cv_status sys::posix_semaphore::wait_until (Lock & lock, const std::chrono::time_point< Clock, Duration > & tp) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semtimedop(2)
sem_timedwait(2)
Definition at line 488 of file semaphore.
References std::chrono::system_clock::now(), and sys::sysv_semaphore::wait_until().
wait_until() [4/4]
template<class Lock , class Clock , class Duration , class Pred > bool sys::posix_semaphore::wait_until (Lock & lock, const std::chrono::time_point< Clock, Duration > & tp, Pred pred) inline
Wait on the semaphore until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
Exceptions
bad_call
See also
semtimedop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 500 of file semaphore.
References std::chrono::system_clock::now(), and sys::sysv_semaphore::wait_until().