UNISTDX: sys::socket Class Reference
sys::socket Class Reference
System abstractions » Network
Socket wrapper.
Public Types
enum option : opt_type {
reuse_addr = SO_REUSEADDR,
keep_alive = SO_KEEPALIVE,
pass_credentials = SO_PASSCRED
}
Socket options.
enum shutdown_how {
shut_read = SHUT_RD,
shut_write = SHUT_WR,
shut_read_write = SHUT_RDWR
}
Socket shutdown options.
typedef std::chrono::system_clock clock_type
Clock type used in this class.
typedef clock_type::duration duration
Duration type.
typedef int protocol_type
Protocol number type.
Public Types inherited from sys::fildes
enum fd_flag : flag_type { fd_close_on_exec = FD_CLOEXEC }
File descriptor flags.
enum pipe_flag : flag_type { no_sigpipe = F_SETNOSIGPIPE }
File descriptor pipe flags.
Public Member Functions
socket (const socket &)=delete
socket & operator= (const socket &)=delete
socket (socket &&rhs) noexcept
Move-constructor.
socket (fildes &&rhs) noexcept
Construct the socket from file descriptor rhs.
socket (const endpoint &bind_addr)
Construct the socket and bind on bind_addr and listen.
socket (const endpoint &bind_addr, const endpoint &conn_addr)
Construct the socket, bind on bind_addr and connect to a process listening on conn_addr.
socket (family_type family, socket_type type=socket_type::stream, protocol_type proto=0)
Construct the socket with protocol family family, type type and protocol proto.
~socket ()
Close the socket.
socket & operator= (socket &&rhs)
Move-assignment.
void bind (const endpoint &e)
Bind on socket address e.
void connect (const endpoint &e)
Connect to socket address e.
void listen ()
Listen on previously binded socket address.
void accept (socket &sock, endpoint &addr)
Accept socket connection.
void shutdown (shutdown_how how)
Shutdown communication on the socket, but do not close it.
void close ()
Shutdown and close the socket.
void setopt (option opt)
Activate socket option.
void set_user_timeout (const duration &d)
Set TCP user timeout option (see RFC 5482).
endpoint bind_addr () const noexcept
Get bound socket address.
endpoint name () const
Get bound socket address.
endpoint peer_name () const
Get address of the client, connected to the socket.
ssize_t send (const message_header &hdr, int flags=0) const
Send low-level message hdr through the socket.
ssize_t receive (message_header &hdr, int flags=0) const
Receive low-level message hdr over the socket.
ssize_t receive (void *buf, size_t n, int flags=0) const
Read n bytes from the socket and store them in buffer pointed by buf.
ssize_t send (const void *buf, size_t n, int flags=0) const
Write n bytes from buffer pointed by buf to the socket.
user_credentials credentials () const
Get UID, GID and PID of the process, that is connected to this socket (client).
void send_fds (const fd_type *data, size_t n)
Send an array of n file descriptors pointed by data.
void receive_fds (fd_type *data, size_t n)
Receive an array of n file descriptors pointed by data.
Public Member Functions inherited from sys::fildes
fildes (const fildes &)=delete
fildes & operator= (const fildes &)=delete
fildes (fd_type rhs) noexcept
Construct file descriptor by wrapping rhs.
fildes (fildes &&rhs) noexcept
Move-constructor.
fildes (const char *filename, open_flag flags, mode_type mode)
~fildes ()
Close file descriptor.
fildes & operator= (fildes &&rhs)
Move assignment.
void close ()
Close file descriptor.
ssize_t read (void *buf, size_t n) const
Read n bytes from file descriptor and store them in the array pointed by buf.
ssize_t write (const void *buf, size_t n) const
Write n bytes to file descriptor copying them from the array pointer by buf.
fd_type fd () const noexcept
Get bare file descriptor.
open_flag flags () const
Get file descriptor open flags.
flag_type fd_flags () const
Get file descriptor flags.
void setf (open_flag rhs)
Set file descriptor open flags.
void unsetf (open_flag rhs)
Unset file descriptor open flags.
void setf (pipe_flag rhs)
Set file descriptor pipe flags.
void unsetf (pipe_flag rhs)
Unset file descriptor pipe flags.
void setf (fd_flag rhs)
Set file descriptor flags.
bool operator== (const fildes &rhs) const noexcept
Compare file descriptors.
operator bool () const noexcept
Returns true, if file descriptor is valid.
bool operator! () const noexcept
Returns true, if file descriptor is invalid.
bool operator== (fd_type rhs) const noexcept
Compare file descriptors.
void remap ()
Change file descriptor number to an arbitrrary one by duplicating it with dup(2) system call.
void remap (fd_type new_fd)
Change file descriptor number to new_fd by duplicating it with dup2(2) system call.
void validate ()
Check if this file descriptor exists in the kernel by trying to get its flags.
void open (const char *filename, open_flag flags, mode_type mode)
Init file descriptor by opening file filename with open flags flags and mode mode.
Static Public Attributes
static const flag_type default_flags
Static Public Attributes inherited from sys::fildes
static const fd_type bad = -1
Invalid file descriptor constant.
Protected Member Functions
socket (fd_type sock) noexcept
Construct the socket with bare file descriptor.
Friends
void swap (socket &lhs, socket &rhs)
Specialisation of std::swap.
std::ostream & operator<< (std::ostream &out, const socket &rhs)
Print socket file descriptor and status.
Additional Inherited Members
Protected Attributes inherited from sys::fildes
fd_type _fd = bad
File descriptor number.
Detailed Description
Socket wrapper.
Date
2018-05-24
Author
Ivan Gankevich
Socket is a file descriptor which is used for communication.
Usually, sockets are used for network communication.
Definition at line 53 of file socket.
Member Enumeration Documentation
option
enum sys::socket::option : opt_type
Socket options.
Enumerator
pass_credentials
Enables sending and receiving UID, GID and PID of the process via unix domain socket.
See also
unix(7)
Definition at line 69 of file socket.
Constructor & Destructor Documentation
socket() [1/3]
sys::socket::socket (const endpoint & bind_addr) explicit
Construct the socket and bind on bind_addr and listen.
Exceptions
bad_call
See also
socket(2)
Definition at line 30 of file socket.cc.
References bind(), and listen().
socket() [2/3]
sys::socket::socket (const endpoint & bind_addr, const endpoint & conn_addr)
Construct the socket, bind on bind_addr and connect to a process listening on conn_addr.
Exceptions
bad_call
See also
socket(2)
Definition at line 35 of file socket.cc.
socket() [3/3]
sys::socket::socket (family_type family, socket_type type = socket_type::stream, protocol_type proto = 0)
Construct the socket with protocol family family, type type and protocol proto.
Exceptions
bad_call
See also
socket(2)
Definition at line 40 of file socket.cc.
Member Function Documentation
accept()
void sys::socket::accept (socket & sock, endpoint & addr)
Accept socket connection.
Date
2018-05-24
Author
Ivan Gankevich
Exceptions
bad_call
See also
accept4(2)
Parameters
[out] sock socket that initiated a connection (client)
[out] addr sockt address of the client
Definition at line 75 of file socket.cc.
References sys::fildes::_fd, close(), sys::endpoint::sockaddr(), and UNISTDX_CHECK.
bind()
void sys::socket::bind (const endpoint & e)
Bind on socket address e.
Exceptions
bad_call
See also
bind(2)
Definition at line 45 of file socket.cc.
References sys::endpoint::sockaddr(), sys::endpoint::sockaddrlen(), and UNISTDX_CHECK.
Referenced by socket().
bind_addr()
endpoint sys::socket::bind_addr () const inline noexcept
Get bound socket address.
See also
getsockname(2)
The same as name, but does not throw.
Definition at line 237 of file socket.
References sys::fildes::_fd, and sys::endpoint::sockaddr().
close()
void sys::socket::close ()
Shutdown and close the socket.
Exceptions
bad_call
See also
shutdown(2)
close(2)
Definition at line 112 of file socket.cc.
References sys::fildes::close().
Referenced by accept(), and ~socket().
connect()
void sys::socket::connect (const endpoint & e)
Connect to socket address e.
Exceptions
bad_call if system error occurs, except std::errc::operation_in_progress
See also
connect(2)
std::errc
Definition at line 63 of file socket.cc.
References sys::endpoint::sockaddr(), sys::endpoint::sockaddrlen(), and UNISTDX_CHECK_IF_NOT.
credentials()
sys::user_credentials sys::socket::credentials () const
Get UID, GID and PID of the process, that is connected to this socket (client).
Exceptions
bad_call
See also
getsockopt(2)
Note
The method works only for unix domain sockets.
Definition at line 245 of file socket.cc.
References UNISTDX_CHECK.
listen()
void sys::socket::listen ()
Listen on previously binded socket address.
Exceptions
bad_call
See also
listen(2)
Definition at line 55 of file socket.cc.
References UNISTDX_CHECK.
Referenced by socket().
name()
endpoint sys::socket::name () const inline
Get bound socket address.
Exceptions
bad_call
See also
getsockname(2)
Definition at line 250 of file socket.
References sys::fildes::_fd, sys::endpoint::sockaddr(), and UNISTDX_CHECK.
peer_name()
endpoint sys::socket::peer_name () const inline
Get address of the client, connected to the socket.
Exceptions
bad_call
See also
getpeername(2)
Definition at line 263 of file socket.
References sys::fildes::_fd, sys::endpoint::sockaddr(), and UNISTDX_CHECK.
receive() [1/2]
ssize_t sys::socket::receive (message_header & hdr, int flags = 0) const inline
Receive low-level message hdr over the socket.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
recvmsg(2)
Definition at line 290 of file socket.
References sys::fildes::_fd, sys::fildes::flags(), and UNISTDX_THROW_BAD_CALL.
Referenced by sys::streambuf_traits< socket >::read(), and sys::receive_credentials().
receive() [2/2]
ssize_t sys::socket::receive (void * buf, size_t n, int flags = 0) const inline
Read n bytes from the socket and store them in buffer pointed by buf.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
recv(2)
Definition at line 306 of file socket.
References sys::fildes::_fd, sys::fildes::flags(), and UNISTDX_THROW_BAD_CALL.
receive_fds()
void sys::socket::receive_fds (sys::fd_type * data, size_t n)
Receive an array of n file descriptors pointed by data.
Exceptions
bad_call
See also
cmsg(3)
unix(7)
Note
The method works only for unix domain sockets.
Definition at line 289 of file socket.cc.
References std::copy_n().
send() [1/2]
ssize_t sys::socket::send (const message_header & hdr, int flags = 0) const inline
Send low-level message hdr through the socket.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
sendmsg(2)
Definition at line 276 of file socket.
References sys::fildes::_fd, sys::fildes::flags(), and UNISTDX_THROW_BAD_CALL.
Referenced by send(), sys::send_credentials(), and sys::streambuf_traits< socket >::write().
send() [2/2]
ssize_t sys::socket::send (const void * buf, size_t n, int flags = 0) const inline
Write n bytes from buffer pointed by buf to the socket.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
send(2)
Definition at line 321 of file socket.
References sys::fildes::_fd, sys::fildes::flags(), send(), and UNISTDX_THROW_BAD_CALL.
send_fds()
void sys::socket::send_fds (const fd_type * data, size_t n)
Send an array of n file descriptors pointed by data.
Exceptions
bad_call
See also
cmsg(3)
unix(7)
Note
The method works only for unix domain sockets.
Definition at line 265 of file socket.cc.
References std::copy_n(), and sys::send().
set_user_timeout()
void sys::socket::set_user_timeout (const duration & d)
Set TCP user timeout option (see RFC 5482).
Exceptions
bad_call
See also
setsockopt(2)
tcp(7)
Definition at line 127 of file socket.cc.
References std::chrono::duration_cast(), and UNISTDX_CHECK.
setopt()
void sys::socket::setopt (option opt)
Activate socket option.
Exceptions
bad_call
See also
setsockopt(2)
Definition at line 118 of file socket.cc.
References UNISTDX_CHECK.
shutdown()
void sys::socket::shutdown (shutdown_how how)
Shutdown communication on the socket, but do not close it.
Exceptions
bad_call if system error occurs, except std::errc::not_connected and std::errc::not_supported
See also
shutdown(2)
std::errc
Definition at line 102 of file socket.cc.
References UNISTDX_THROW_BAD_CALL.
Member Data Documentation
default_flags
const flag_type sys::socket::default_flags static
Initial value:
=
            UNISTDX_SOCK_NONBLOCK | UNISTDX_SOCK_CLOEXEC
Default socket flags. The socket is non-blocking and automatically closed on child process execution.
Definition at line 91 of file socket.