UNISTDX: sys::sysv_semaphore Class Reference
sys::sysv_semaphore Class Reference
System abstractions » ProcessesC++ concepts » | Semaphores
Semaphore, implemented using System V system calls.
Public Types
typedef int sem_type
Alias to system semaphore type (int).
typedef std::chrono::system_clock clock_type
Clock type used in this class.
Public Member Functions
sysv_semaphore (mode_type mode=0600)
Construct semaphore with specified mode.
sysv_semaphore (sem_type sem)
Construct semaphore with ID sem.
~sysv_semaphore ()
Remove semaphore (if owner). Terminates on system error.
sem_type id () const noexcept
Get semaphore ID.
bool owner () const noexcept
Check if this semaphore is owned by this process.
void wait ()
Wait until other process/thread calls sysv_semaphore::notify_one or sysv_semaphore::notify_all on this semaphore.
void notify_one ()
Notify one process that wait on this semaphore.
void notify_all ()
Notify all processes that wait on this semaphore.
void notify_all (int n)
Notify n processes that wait on this semaphore.
template<class Lock >
void wait (Lock &lock)
Wait on the semaphore unlocking lock for the duration of the wait.
template<class Lock , class Pred >
void wait (Lock &lock, Pred pred)
Wait on the semaphore unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Rep , class Period >
std::cv_status wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur)
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait.
template<class Lock , class Rep , class Period , class Pred >
bool wait_for (Lock &lock, const std::chrono::duration< Rep, Period > &dur, Pred pred)
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
template<class Lock , class Duration >
std::cv_status wait_until (Lock &lock, const std::chrono::time_point< clock_type, Duration > &tp)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Duration , class Pred >
bool wait_until (Lock &lock, const std::chrono::time_point< clock_type, Duration > &tp, Pred pred)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
template<class Lock , class Clock , class Duration >
std::cv_status wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp)
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
template<class Lock , class Clock , class Duration , class Pred >
bool wait_until (Lock &lock, const std::chrono::time_point< Clock, Duration > &tp, Pred pred)
Wait on the semaphore until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Detailed Description
Semaphore, implemented using System V system calls.
Date
2018-05-21
Author
Ivan Gankevich
Suitable for both processes and threads.
Definition at line 52 of file semaphore.
Constructor & Destructor Documentation
sysv_semaphore() [1/2]
sys::sysv_semaphore::sysv_semaphore (mode_type mode = 0600) inline explicit
Construct semaphore with specified mode.
Exceptions
bad_call
See also
semget(2)
The semaphore is owned by the calling process/thread.
Definition at line 72 of file semaphore.
References UNISTDX_CHECK.
sysv_semaphore() [2/2]
sys::sysv_semaphore::sysv_semaphore (sem_type sem) inline explicit
Construct semaphore with ID sem.
The semaphore is not owned by the calling process/thread.
Definition at line 86 of file semaphore.
~sysv_semaphore()
sys::sysv_semaphore::~sysv_semaphore () inline
Remove semaphore (if owner). Terminates on system error.
See also
semctl(2)
Definition at line 96 of file semaphore.
References UNISTDX_CHECK.
Member Function Documentation
notify_all() [1/2]
void sys::sysv_semaphore::notify_all () inline
Notify all processes that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 160 of file semaphore.
Referenced by sys::posix_semaphore::notify_all().
notify_all() [2/2]
void sys::sysv_semaphore::notify_all (int n) inline
Notify n processes that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 170 of file semaphore.
notify_one()
void sys::sysv_semaphore::notify_one () inline
Notify one process that wait on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 150 of file semaphore.
Referenced by sys::posix_semaphore::notify_all().
wait() [1/3]
void sys::sysv_semaphore::wait () inline
Wait until other process/thread calls sysv_semaphore::notify_one or sysv_semaphore::notify_all on this semaphore.
Exceptions
bad_call
See also
semop(2)
Definition at line 140 of file semaphore.
Referenced by wait(), and sys::posix_semaphore::wait().
wait() [2/3]
template<class Lock > void sys::sysv_semaphore::wait (Lock & lock) inline
Wait on the semaphore unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semop(2)
Definition at line 180 of file semaphore.
References wait().
wait() [3/3]
template<class Lock , class Pred > void sys::sysv_semaphore::wait (Lock & lock, Pred pred) inline
Wait on the semaphore unlocking lock for the duration of the wait until predicate pred becomes true.
Exceptions
bad_call
See also
semop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 197 of file semaphore.
References wait().
wait_for() [1/2]
template<class Lock , class Rep , class Period > std::cv_status sys::sysv_semaphore::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur) inline
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semtimedop(2)
Definition at line 213 of file semaphore.
References std::chrono::nanoseconds::count(), std::chrono::duration_cast(), and std::max().
Referenced by wait_for(), and wait_until().
wait_for() [2/2]
template<class Lock , class Rep , class Period , class Pred > bool sys::sysv_semaphore::wait_for (Lock & lock, const std::chrono::duration< Rep, Period > & dur, Pred pred) inline
Wait on the semaphore specified amount of time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
Exceptions
bad_call
See also
semtimedop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 238 of file semaphore.
References wait_for().
wait_until() [1/4]
template<class Lock , class Duration > std::cv_status sys::sysv_semaphore::wait_until (Lock & lock, const std::chrono::time_point< clock_type, Duration > & tp) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semtimedop(2)
Definition at line 256 of file semaphore.
References std::chrono::system_clock::now(), and wait_for().
Referenced by sys::posix_semaphore::wait_for(), and sys::posix_semaphore::wait_until().
wait_until() [2/4]
template<class Lock , class Duration , class Pred > bool sys::sysv_semaphore::wait_until (Lock & lock, const std::chrono::time_point< clock_type, Duration > & tp, Pred pred) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait until predicate pred becomes true.
Returns
predicate value
Exceptions
bad_call
See also
semtimedop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 275 of file semaphore.
References std::chrono::system_clock::now(), and wait_for().
wait_until() [3/4]
template<class Lock , class Clock , class Duration > std::cv_status sys::sysv_semaphore::wait_until (Lock & lock, const std::chrono::time_point< Clock, Duration > & tp) inline
Wait on the semaphore until specified time tp unlocking lock for the duration of the wait.
Exceptions
bad_call
See also
semtimedop(2)
Definition at line 288 of file semaphore.
References wait_for().
wait_until() [4/4]
template<class Lock , class Clock , class Duration , class Pred > bool sys::sysv_semaphore::wait_until (Lock & lock, const std::chrono::time_point< Clock, Duration > & tp, Pred pred) inline
Wait on the semaphore until specified time dur unlocking lock for the duration of the wait until predicate pred becomes true or timeout occurs.
Returns
predicate value
Exceptions
bad_call
See also
semtimedop(2)
If pred is true upon the call to this method no waiting or unlocking is done
The mutex is locked when checking for the predicate.
Definition at line 307 of file semaphore.
References wait_for().