UNISTDX: sys::ifaddr< Addr > Class Template Reference
sys::ifaddr< Addr > Class Template Reference
System abstractions » Network
Network interface address.
Public Types
typedef Addr addr_type
Address type.
typedef ipaddr_traits< Addr > traits_type
Address traits type.
typedef addr_type::rep_type rep_type
Address representation type.
typedef subnet_iterator< addr_type > iterator
Address iterator type.
Public Member Functions
constexpr ifaddr (const addr_type &addr, const addr_type &netmask) noexcept
constexpr ifaddr (const addr_type &addr, const prefix_type prefix) noexcept
constexpr ifaddr (const ifaddr &) noexcept=default
Copy-constructor.
constexpr ifaddr (ifaddr &&) noexcept=default
Move-constructor.
ifaddr & operator= (const ifaddr &) noexcept=default
Assignment.
constexpr const addr_type & address () const noexcept
Get address.
constexpr const addr_type & netmask () const noexcept
Get network mask.
prefix_type prefix () const noexcept
Get network prefix.
constexpr const addr_type & gateway () const noexcept
Get network gateway address.
constexpr rep_type position () const noexcept
Get position of interface address in its subnetwork.
constexpr iterator begin () const noexcept
Get iterator to the beginning of the subnetwork.
constexpr iterator middle () const noexcept
Get iterator to this interface address in the subnetwork.
constexpr iterator end () const noexcept
Get iterator to the end of the subnetwork.
constexpr rep_type count () const noexcept
constexpr bool contains (const addr_type &rhs) const noexcept
constexpr rep_type first () const noexcept
Get the first address in the network (gateway address).
constexpr rep_type last () const noexcept
Get the last address in the network (broadcast address).
constexpr bool is_loopback () const noexcept
Returns true, if the subnetwork is loopback.
constexpr bool is_widearea () const noexcept
Returns true, if the subnetwork is widearea.
constexpr operator bool () const noexcept
constexpr bool operator! () const noexcept
constexpr bool operator== (const ifaddr &rhs) const noexcept
Compares addresses and network masks.
constexpr bool operator!= (const ifaddr &rhs) const noexcept
Compares addresses and network masks.
constexpr bool operator< (const ifaddr &rhs) const noexcept
Compares addresses and network masks.
Friends
template<class X >
class std::hash
std::ostream & operator<< (std::ostream &out, const ifaddr &rhs)
Put address and network prefix.
std::istream & operator>> (std::istream &in, ifaddr &rhs)
Get address and network prefix.
bstream & operator<< (bstream &out, const ifaddr &rhs)
Put interface address in binary form.
bstream & operator>> (bstream &in, ifaddr &rhs)
Get interface address in binary form.
Detailed Description
template<class Addr>
class sys::ifaddr< Addr >
Network interface address.
Date
2018-05-23
Author
Ivan Gankevich
Definition at line 21 of file ifaddr.
Constructor & Destructor Documentation
ifaddr() [1/2]
template<class Addr> constexpr sys::ifaddr< Addr >::ifaddr (const addr_type & addr, const addr_type & netmask) inline noexcept
Construct interface address from address addr and network mask netmask.
Definition at line 44 of file ifaddr.
ifaddr() [2/2]
template<class Addr> constexpr sys::ifaddr< Addr >::ifaddr (const addr_type & addr, const prefix_type prefix) inline noexcept
Construct interface address from address addr and network prefix prefix.
Definition at line 53 of file ifaddr.
Member Function Documentation
contains()
template<class Addr> constexpr bool sys::ifaddr< Addr >::contains (const addr_type & rhs) const inline noexcept
Returns true, of the subnetwork contains address rhs.
Definition at line 133 of file ifaddr.
References sys::to_host_format().
count()
template<class Addr> constexpr rep_type sys::ifaddr< Addr >::count () const inline noexcept
Return the number of addresses in the subnetwork, including gateway and broadcast addresses.
Definition at line 125 of file ifaddr.
References sys::ifaddr< Addr >::first(), and sys::ifaddr< Addr >::last().
operator bool()
template<class Addr> constexpr sys::ifaddr< Addr >::operator bool () const inline explicit noexcept
Returns true, if both address and network mask are valid (non-nought).
Definition at line 167 of file ifaddr.
operator!()
template<class Addr> constexpr bool sys::ifaddr< Addr >::operator! () const inline noexcept
Returns true, if either address or network mask is invalid (equals nought).
Definition at line 176 of file ifaddr.