UNISTDX: sys::process Class Reference
sys::process Class Reference
System abstractions » Processes
System process with std::thread interface.
Public Member Functions
template<class F >
process (F f, process_flag pf=process_flag::fork)
Construct new process by forking a child with f as main function.
process (pid_type rhs) noexcept
Construct process by its ID.
process (const process &)=delete
process (process &&rhs) noexcept
Move-constructor.
~process ()
Terminates the process, if any.
process & operator= (process &&rhs) noexcept
Move-assignment.
void terminate ()
void kill ()
Forcibly terminate the process by sending signal::kill signal.
void interrupt ()
Interrupt the process by sending signal::keyboard_interrupt signal.
void hang_up ()
Interrupt the process by sending signal::hang_up signal.
void send (sys::signal s)
Send signal s to the process.
sys::proc_status wait ()
Wait until process changes its state or terminates.
operator bool () const noexcept
Check if process is alive by sending nought signal to it.
bool operator! () const noexcept
Check if process is alive by sending nought signal to it.
void swap (process &rhs)
Swap with rhs.
pid_type id () const noexcept
Get process ID.
pid_type group_id () const noexcept
Get process group ID.
void set_group_id (pid_type rhs) const
Set process group ID.
bool joinable ()
Always returns true to be compatible with std::thread.
void join ()
Wait until process changes its state or terminates.
Friends
std::ostream & operator<< (std::ostream &out, const process &rhs)
Output process ID and process group ID.
Detailed Description
System process with std::thread interface.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 187 of file process.
Constructor & Destructor Documentation
process()
template<class F > sys::process::process (F f, process_flag pf = process_flag::fork) inline explicit
Construct new process by forking a child with f as main function.
Exceptions
bad_call
See also
clone(2)
fork(2)
Definition at line 199 of file process.
Member Function Documentation
group_id()
pid_type sys::process::group_id () const inline noexcept
Get process group ID.
See also
getpgid(2)
Definition at line 361 of file process.
Referenced by sys::operator<<().
hang_up()
void sys::process::hang_up () inline
Interrupt the process by sending signal::hang_up signal.
Exceptions
bad_call
See also
kill(2)
Definition at line 297 of file process.
References sys::hang_up, and send().
interrupt()
void sys::process::interrupt () inline
Interrupt the process by sending signal::keyboard_interrupt signal.
Exceptions
bad_call
See also
kill(2)
Definition at line 286 of file process.
References sys::keyboard_interrupt, and send().
join()
void sys::process::join () inline
Wait until process changes its state or terminates.
Exceptions
bad_call if system error occurs, except std::errc::interrupted
See also
std::errc
waitpid(2)
Definition at line 383 of file process.
References wait().
kill()
void sys::process::kill () inline
Forcibly terminate the process by sending signal::kill signal.
Exceptions
bad_call
See also
kill(2)
Definition at line 274 of file process.
References sys::kill, and send().
send()
void sys::process::send (sys::signal s) inline
Send signal s to the process.
Exceptions
bad_call
Definition at line 306 of file process.
References UNISTDX_CHECK.
Referenced by hang_up(), interrupt(), kill(), and terminate().
set_group_id()
void sys::process::set_group_id (pid_type rhs) const inline
Set process group ID.
Exceptions
bad_call
See also
setpgid(2)
Definition at line 371 of file process.
References UNISTDX_CHECK.
terminate()
void sys::process::terminate () inline
Gracefully terminate the process by sending signal::terminate signal.
See also
kill(2)
Definition at line 262 of file process.
References send(), and sys::terminate.
wait()
sys::proc_status sys::process::wait () inline
Wait until process changes its state or terminates.
Exceptions
bad_call if system error occurs, except std::errc::interrupted
See also
std::errc
waitpid(2)
Definition at line 320 of file process.
References UNISTDX_CHECK_IF_NOT.
Referenced by join().