UNISTDX: sys::fildes Class Reference
sys::fildes Class Reference
System abstractions » WrappersSystem abstractions » | IO
File descriptor wrapper.
Public Types
enum fd_flag : flag_type { fd_close_on_exec = FD_CLOEXEC }
File descriptor flags.
enum pipe_flag : flag_type { no_sigpipe = F_SETNOSIGPIPE }
File descriptor pipe flags.
Public Member Functions
fildes (const fildes &)=delete
fildes & operator= (const fildes &)=delete
fildes (fd_type rhs) noexcept
Construct file descriptor by wrapping rhs.
fildes (fildes &&rhs) noexcept
Move-constructor.
fildes (const char *filename, open_flag flags, mode_type mode)
~fildes ()
Close file descriptor.
fildes & operator= (fildes &&rhs) noexcept
Move-assignment.
void close ()
Close file descriptor.
ssize_t read (void *buf, size_t n) const
Read n bytes from file descriptor and store them in the array pointed by buf.
ssize_t write (const void *buf, size_t n) const
Write n bytes to file descriptor copying them from the array pointer by buf.
fd_type fd () const noexcept
Get bare file descriptor.
open_flag flags () const
Get file descriptor open flags.
flag_type fd_flags () const
Get file descriptor flags.
void setf (open_flag rhs)
Set file descriptor open flags.
void unsetf (open_flag rhs)
Unset file descriptor open flags.
void setf (pipe_flag rhs)
Set file descriptor pipe flags.
void unsetf (pipe_flag rhs)
Unset file descriptor pipe flags.
void setf (fd_flag rhs)
Set file descriptor flags.
bool operator== (const fildes &rhs) const noexcept
Compare file descriptors.
operator bool () const noexcept
Returns true, if file descriptor is valid.
bool operator! () const noexcept
Returns true, if file descriptor is invalid.
bool operator== (fd_type rhs) const noexcept
Compare file descriptors.
void swap (fildes &rhs) noexcept
Swap with rhs.
void remap ()
Change file descriptor number to an arbitrrary one by duplicating it with dup(2) system call.
void remap (fd_type new_fd)
Change file descriptor number to new_fd by duplicating it with dup2(2) system call.
void validate ()
Check if this file descriptor exists in the kernel by trying to get its flags.
void open (const char *filename, open_flag flags, mode_type mode)
Init file descriptor by opening file filename with open flags flags and mode mode.
Static Public Attributes
static const fd_type bad = -1
Invalid file descriptor constant.
Protected Attributes
fd_type _fd = bad
File descriptor number.
Friends
bool operator== (fd_type lhs, const fildes &rhs) noexcept
Compare file descriptors.
std::ostream & operator<< (std::ostream &out, const fildes &rhs)
Output file descriptor number.
Detailed Description
File descriptor wrapper.
Date
2018-05-22
Author
Ivan Gankevich
Definition at line 33 of file fildes.
Constructor & Destructor Documentation
fildes()
sys::fildes::fildes (const char * filename, open_flag flags, mode_type mode) inline
Construct file descriptor by opening file filename with open flags flags and mode mode.
Definition at line 80 of file fildes.
References flags(), and open().
~fildes()
sys::fildes::~fildes () inline
Close file descriptor.
The method ignores errors reported by close(2) system call.
Definition at line 90 of file fildes.
References close().
Member Function Documentation
close()
void sys::fildes::close () inline
Close file descriptor.
Exceptions
bad_call if close(2) system call fails
See also
close(2)
Definition at line 123 of file fildes.
References bad, and UNISTDX_CHECK.
Referenced by sys::fildes_pair::close(), sys::socket::close(), open(), remap(), and ~fildes().
fd_flags()
flag_type sys::fildes::fd_flags () const inline
Get file descriptor flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 178 of file fildes.
flags()
open_flag sys::fildes::flags () const inline
Get file descriptor open flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 168 of file fildes.
Referenced by fildes(), sys::file_mutex::file_mutex(), open(), sys::socket::receive(), and sys::socket::send().
open()
void sys::fildes::open (const char * filename, open_flag flags, mode_type mode) inline
Init file descriptor by opening file filename with open flags flags and mode mode.
Exceptions
bad_call
Definition at line 314 of file fildes.
References close(), and flags().
Referenced by fildes().
read()
ssize_t sys::fildes::read (void * buf, size_t n) const inline
Read n bytes from file descriptor and store them in the array pointed by buf.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
read(2)
Definition at line 137 of file fildes.
References UNISTDX_CHECK_IO.
Referenced by sys::netlink_container< T >::read().
remap() [1/2]
void sys::fildes::remap ()
Change file descriptor number to an arbitrrary one by duplicating it with dup(2) system call.
Exceptions
bad_call
See also
dup(2)
Definition at line 6 of file fildes.cc.
References _fd, close(), and UNISTDX_CHECK.
remap() [2/2]
void sys::fildes::remap (fd_type new_fd)
Change file descriptor number to new_fd by duplicating it with dup2(2) system call.
Exceptions
bad_call
See also
dup2(2)
Definition at line 14 of file fildes.cc.
References UNISTDX_CHECK.
setf() [1/3]
void sys::fildes::setf (open_flag rhs) inline
Set file descriptor open flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 188 of file fildes.
setf() [2/3]
void sys::fildes::setf (pipe_flag rhs) inline
Set file descriptor pipe flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 209 of file fildes.
setf() [3/3]
void sys::fildes::setf (fd_flag rhs) inline
Set file descriptor flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 230 of file fildes.
unsetf() [1/2]
void sys::fildes::unsetf (open_flag rhs) inline
Unset file descriptor open flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 198 of file fildes.
unsetf() [2/2]
void sys::fildes::unsetf (pipe_flag rhs) inline
Unset file descriptor pipe flags.
Exceptions
bad_call
See also
fcntl(2)
Definition at line 219 of file fildes.
validate()
void sys::fildes::validate () inline
Check if this file descriptor exists in the kernel by trying to get its flags.
Exceptions
bad_call
Definition at line 303 of file fildes.
Referenced by sys::two_way_pipe::validate().
write()
ssize_t sys::fildes::write (const void * buf, size_t n) const inline
Write n bytes to file descriptor copying them from the array pointer by buf.
Exceptions
bad_call if system error occurs, except std::errc::resource_unavailable_try_again and std::errc::operation_in_progress
See also
std::errc
write(2)
Definition at line 150 of file fildes.
References UNISTDX_CHECK_IO.
Referenced by sys::event_poller::notify_one().