UNISTDX: sys::file_mutex Class Reference
sys::file_mutex Class Reference
C++ concepts » MutexesSystem abstractions » | File system
File-based mutex.
Public Member Functions
void lock (file_lock_type tp=file_lock_type::write_lock)
Acquire file lock of type tp.
void unlock ()
Release file lock.
bool try_lock (file_lock_type tp=file_lock_type::write_lock)
Try to acquire file lock of type tp.
file_mutex (const char *filename, open_flag flags, mode_type mode) noexcept
file_mutex (const char *filename, mode_type mode) noexcept
void open (const char *filename, mode_type mode) noexcept
void open (const char *filename, open_flag flags, mode_type mode) noexcept
Public Member Functions inherited from sys::fildes
fildes (const fildes &)=delete
fildes & operator= (const fildes &)=delete
fildes (fd_type rhs) noexcept
Construct file descriptor by wrapping rhs.
fildes (fildes &&rhs) noexcept
Move-constructor.
fildes (const char *filename, open_flag flags, mode_type mode)
~fildes ()
Close file descriptor.
fildes & operator= (fildes &&rhs)
Move assignment.
void close ()
Close file descriptor.
ssize_t read (void *buf, size_t n) const
ssize_t write (const void *buf, size_t n) const
fd_type fd () const noexcept
Get bare file descriptor.
open_flag flags () const
Get file descriptor open flags.
flag_type fd_flags () const
Get file descriptor flags.
void setf (open_flag rhs)
Set file descriptor open flags.
void unsetf (open_flag rhs)
Unset file descriptor open flags.
void setf (pipe_flag rhs)
Set file descriptor pipe flags.
void unsetf (pipe_flag rhs)
Unset file descriptor pipe flags.
void setf (fd_flag rhs)
Set file descriptor flags.
bool operator== (const fildes &rhs) const noexcept
Compare file descriptors.
operator bool () const noexcept
Returns true, if file descriptor is valid.
bool operator! () const noexcept
Returns true, if file descriptor is invalid.
bool operator== (fd_type rhs) const noexcept
Compare file descriptors.
void remap ()
void remap (fd_type new_fd)
void validate ()
void open (const char *filename, open_flag flags, mode_type mode)
Additional Inherited Members
Public Types inherited from sys::fildes
enum fd_flag : flag_type { fd_close_on_exec = FD_CLOEXEC }
File descriptor flags.
enum pipe_flag : flag_type { no_sigpipe = F_SETNOSIGPIPE }
File descriptor pipe flags.
Static Public Attributes inherited from sys::fildes
static const fd_type bad = -1
Invalid file descriptor constant.
Protected Attributes inherited from sys::fildes
fd_type _fd = bad
File descriptor number.
Detailed Description
File-based mutex.
Date
2018-05-21
Author
Ivan Gankevich
See also
flock(2)
Uses the sanest (but not very portable) flock(2) system call for file locking.
Read locks may be acquired by multiple processes, provided that there no write lock on the file.
Write lock may be acquired by only one process.
Definition at line 54 of file file_mutex.
Constructor & Destructor Documentation
file_mutex() [1/2]
sys::file_mutex::file_mutex (const char * filename, open_flag flags, mode_type mode) inline noexcept
Construct file mutex with file filename, flags flags, file mode mode.
Definition at line 77 of file file_mutex.
References sys::fildes::flags(), and open().
file_mutex() [2/2]
sys::file_mutex::file_mutex (const char * filename, mode_type mode) inline noexcept
Construct file mutex with file filename, read-write permissions, file mode mode.
Definition at line 91 of file file_mutex.
References open().
Member Function Documentation
open() [1/2]
void sys::file_mutex::open (const char * filename, mode_type mode) inline noexcept
Open file filename for mutex with read-write permissions and file mode mode.
Definition at line 101 of file file_mutex.
Referenced by file_mutex().
open() [2/2]
void sys::file_mutex::open (const char * filename, open_flag flags, mode_type mode) noexcept
Open file filename for mutex with flags flags and file mode mode.
Definition at line 15 of file file_mutex.cc.