UNISTDX: sys::basic_odirectory< Trans > Class Template Reference
sys::basic_odirectory< Trans > Class Template Reference
C++ concepts » StreamsSystem abstractions » | File system
Directory entry output stream.
Public Types
typedef Trans transform
File name transformation function type.
Public Member Functions
basic_odirectory (const path &dir)
Construct directory entry output stream for path dir.
basic_odirectory (const basic_odirectory &)=delete
Copy-constructor.
basic_odirectory (basic_odirectory &&)=default
Move-constructor.
void open (const path &dir)
Set directory dir as output directory.
const path & getpath () const noexcept
Get output directory path.
void settransform (transform rhs)
Set file name transformation function.
const transform & gettransform () const noexcept
Get file name transformation function.
operator bool () const noexcept
Always returns true.
bool operator! () const noexcept
Always returns false.
basic_odirectory & operator<< (const direntry &rhs)
Copy directory entry rhs to output directory of the stream.
basic_odirectory & operator<< (const pathentry &rhs)
Copy directory entry rhs to output directory of the stream.
template<class FilePred >
basic_odirectory & operator<< (basic_idirectory< FilePred > &rhs)
Copy all files in directory rhs to output directory of the stream.
template<class X , class Y >
basic_odirectory & operator<< (basic_idirtree< X, Y > &rhs)
Recursively copy whole directory rhs to output directory of the stream.
Detailed Description
template<class Trans>
class sys::basic_odirectory< Trans >
Directory entry output stream.
Date
2018-05-25
Author
Ivan Gankevich
Template Parameters
Trans transformation function type
See also
direntry
pathentry
copy_file
An output stream to which directory entries are written.
Files are copied to output directory on insertion to the stream.
Definition at line 25 of file odirectory.
Member Function Documentation
operator<<()
template<class Trans > basic_odirectory& sys::basic_odirectory< Trans >::operator<< (const pathentry & rhs) inline
Copy directory entry rhs to output directory of the stream.
Exceptions
bad_call
See also
mkdir(2)
copy_file
Definition at line 104 of file odirectory.
References sys::copy_file(), sys::directory, sys::get_file_type(), and sys::pathentry::getpath().