UNISTDX: sys::epoll_event Class Reference
sys::epoll_event Class Reference
System abstractions » WrappersSystem abstractions » | IO
File descriptor event wrapper for event_poller.
Public Member Functions
epoll_event (fd_type f, event ev) noexcept
Construct object from file descriptor f and event mask ev.
epoll_event & operator= (const epoll_event &)=default
Assignment.
E events () const noexcept
Get event mask.
fd_type fd () const noexcept
Get file descriptor.
void disable () noexcept
Disable polling by setting file descriptor to -1.
bool bad_fd () const noexcept
Returns true, if file descriptor is invalid.
bool in () const noexcept
Returns true, if input event occurred.
bool out () const noexcept
Returns true, if output event occurred.
bool hup () const noexcept
bool err () const noexcept
Returns true, if an error occurred.
bool bad () const noexcept
Returns true, if an error or hang up occurred.
void setev (event rhs) noexcept
Set events rhs in event mask.
void unsetev (event rhs) noexcept
Unset events rhs in event mask.
ssize_t probe () const noexcept
Probe file descriptor by peeking a byte from it.
bool operator== (const epoll_event &rhs) const noexcept
Returns true, if events have the same file descriptor.
bool operator!= (const epoll_event &rhs) const noexcept
Returns true, if events have different file descriptors.
bool operator< (const epoll_event &rhs) const noexcept
Compares file descriptors.
operator bool () const noexcept
bool operator! () const noexcept
Friends
std::ostream & operator<< (std::ostream &out, const epoll_event &rhs)
Output file descriptor and event mask for debugging.
Detailed Description
File descriptor event wrapper for event_poller.
Date
2018-05-22
Author
Ivan Gankevich
Definition at line 80 of file epoll_event.
Member Function Documentation
hup()
bool sys::epoll_event::hup () const inline noexcept
Returns true, if hang up event occurred (the other end of the channel was closed).
Definition at line 147 of file epoll_event.
References events().
Referenced by sys::operator<<().
operator bool()
sys::epoll_event::operator bool () const inline explicit noexcept
Returns true, if file descriptor is valid and no bad events occurred.
Definition at line 205 of file epoll_event.
References bad(), and bad_fd().
operator!()
bool sys::epoll_event::operator! () const inline noexcept
Returns true, if either file descriptor is invalid, or a bad event occurred.
Definition at line 214 of file epoll_event.