UNISTDX: sys::signal_guard Class Reference
sys::signal_guard Class Reference
System abstractions » ProcessesC++ concepts » | Guards
Blocks/unblocks specified signals upon creation/destruction.
Public Member Functions
signal_guard (sigset_type s)
Construct signal guard that blocks all signals in set s.
~signal_guard ()
Terminates if unlock fails.
void lock ()
Block all specified signals.
void unlock ()
Unblock all specified signals.
Detailed Description
Blocks/unblocks specified signals upon creation/destruction.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 237 of file signal.
Constructor & Destructor Documentation
signal_guard()
sys::signal_guard::signal_guard (sigset_type s) inline explicit
Construct signal guard that blocks all signals in set s.
Exceptions
bad_call
See also
sigprocmask(2)
Definition at line 250 of file signal.
References lock().
Member Function Documentation
lock()
void sys::signal_guard::lock () inline
Block all specified signals.
Exceptions
bad_call
See also
sigprocmask(2)
Definition at line 271 of file signal.
Referenced by signal_guard().
unlock()
void sys::signal_guard::unlock () inline
Unblock all specified signals.
Exceptions
bad_call
See also
sigprocmask(2)
Definition at line 281 of file signal.
Referenced by ~signal_guard().