UNISTDX: File system
File system
System abstractions
File and directory manipulation.
Classes
class sys::basic_canonical_path< Ch, Tr, Alloc >
Canonical path that is always absolute and real.
class sys::basic_directory< FilePred, Trans >
Directory entry input/output stream.
class sys::direntry
Directory entry.
class sys::dirstream
Base class for all directory streams.
class sys::file_mode
File mode wrapper.
class sys::file_mutex
File-based mutex.
class sys::file_stat
File status class that wraps stat system type.
class sys::basic_idirectory< FilePred >
Directory entry input stream.
struct sys::ignore_hidden_files
Do not include hidden file when traversing directories.
class sys::basic_idirtree< FilePred, DirPred >
Recursive directory entry input stream.
struct sys::ignore_hidden_dirs
Do not recurse to hidden directories when traversing directories.
class sys::basic_odirectory< Trans >
Directory entry output stream.
struct sys::copy_recursively
Copy files and directories recursively.
class sys::basic_path< Ch, Tr, Alloc >
File system path template which is a std::string with additional methods.
class sys::pathentry
Directory entry with a path to directory.
Typedefs
typedef basic_canonical_path< char > sys::canonical_path
Specialisation of basic_canonical_path for char.
typedef basic_idirectory< ignore_hidden_files > sys::idirectory
Directory entry input stream that ignores all hidden files during traversal.
template<class T >
using sys::idirectory_iterator = basic_istream_iterator< idirectory, T >
Directory entry input stream iterator.
typedef basic_idirtree< ignore_hidden_files, ignore_hidden_dirs > sys::idirtree
Recursive directory entry input stream that ignores all hidden files during traversal and does not recurse to hidden directories.
template<class T >
using sys::idirtree_iterator = basic_istream_iterator< idirtree, T >
Recursive directory entry input stream iterator.
typedef basic_odirectory< copy_verbatim > sys::odirectory
Directory entry output stream that copies all files verbatim.
template<class T >
using sys::odirectory_iterator = basic_ostream_iterator< odirectory, T >
Directory entry output stream iterator.
template<class Trans >
using sys::basic_odirtree = basic_odirectory< Trans >
The same template as basic_odirectory.
typedef basic_odirtree< copy_recursively > sys::odirtree
Directory entry output stream that copies all files and directories recursively.
template<class T >
using sys::odirtree_iterator = basic_ostream_iterator< odirtree, T >
Directory entry output stream iterator.
typedef basic_path< char > sys::path
Specialisation of basic_path for char.
Enumerations
enum sys::file_type : mode_type {
sys::file_type::regular = S_IFREG,
sys::file_type::directory = S_IFDIR,
sys::file_type::block_device = S_IFBLK,
sys::file_type::character_device = S_IFCHR,
sys::file_type::pipe = S_IFIFO,
sys::file_type::socket = S_IFSOCK,
sys::file_type::symbolic_link = S_IFLNK
}
Functions
sys::canonical_path sys::this_process::workdir ()
Get canonical path to the working directory of the calling process.
void sys::copy_file (const path &src, const path &dest)
Copy file using the most optimal system call.
void sys::mkdirs (path dir, file_mode m=0755, path::size_type offset=0)
Make directories recursively.
void sys::mkdirs (const path &root, const path &relative_path, file_mode m=0755)
Make directories recursively.
Detailed Description
File and directory manipulation.
Enumeration Type Documentation
file_type
enum sys::file_type : mode_type strong
File types.
Enumerator
regular
Regular file.
directory
A directory.
block_device
Block device.
character_device
Character device.
pipe
Named pipe.
See also
fifo(7)
socket
UNIX domain socket.
See also
unix(7)
symbolic_link
Symbolic link.
Definition at line 15 of file file_type.
Function Documentation
copy_file()
void sys::copy_file (const path & src, const path & dest)
Copy file using the most optimal system call.
Date
2018-05-25
Author
Ivan Gankevich
See also
copy_file_range(2)
sendfile(2)
Exceptions
bad_call
Uses copy_file_range(2) on newer kernels.
Uses sendfile(2) when available.
Otherwise, falls back to standard stream copying.
Definition at line 61 of file copy_file.cc.
References sys::file_stat::size(), and UNISTDX_THROW_BAD_CALL.
Referenced by sys::basic_odirectory< Trans >::operator<<().
mkdirs() [1/2]
void sys::mkdirs (sys::path dir, file_mode m = 0755, path::size_type offset = 0)
Make directories recursively.
Date
2018-04-25
Author
Ivan Gankevich
Exceptions
bad_call
Parameters
[in] dir path, components of which are created
[in] m file mode of directories to be created
[in] offset character offset in path name to start creating directories from
See also
mkdir(2)
Create directories assuming all path components that come before offset characters from the beginning of dir exist.
Definition at line 8 of file mkdirs.cc.
References std::basic_string::size(), and UNISTDX_THROW_BAD_CALL.
mkdirs() [2/2]
void sys::mkdirs (const path & root, const path & relative_path, file_mode m = 0755) inline
Make directories recursively.
Date
2018-04-25
Author
Ivan Gankevich
Exceptions
bad_call
Parameters
[in] root path, relative to which directories are created
[in] relative_path path, components of which are created
[in] m file mode of directories to be created
See also
mkdir(2)
Create directories relative to root assuming that the root exists.
Definition at line 42 of file mkdirs.
References std::basic_string::size().