UNISTDX: Processes
Processes
System abstractions
Resource management and parallel execution.
Classes
class sys::basic_argbuf< Ch, Tr >
Stream buffer for command line arguments.
class sys::argstream
Output stream of command line arguments.
struct sys::basic_status< T >
Base class for process status.
struct sys::basic_status< siginfo_type >
A basic_status object that tells how the process was terminated.
struct sys::basic_status< wstat_type >
A basic_status object that tells how the process was terminated.
class sys::process
System process with std::thread interface.
class sys::process_group
A group of processes.
class sys::process_semaphore
Process semaphore.
class sys::sysv_semaphore
Semaphore, implemented using System V system calls.
class sys::posix_semaphore
Semaphore, implemented using POSIX system calls.
class sys::shared_mem< T >
A container that stores its elements in shared memory.
class sys::basic_shmembuf< Ch, Tr >
Shared memory stream buffer with synchronisation via process_semaphore.
class sys::signal_action
Signal callback.
class sys::sigset_type
Signal set.
class sys::signal_guard
Blocks/unblocks specified signals upon creation/destruction.
class sys::thread_semaphore
Thread semaphore.
Typedefs
typedef ::siginfo_t sys::siginfo_type
Alias for signinfo_t;.
typedef ::pid_t sys::pid_type
Alias for pid_t;.
typedef basic_status< siginfo_type > sys::proc_info
Alias for basic_status<siginfo_type>.
typedef int sys::wstat_type
Alias for status type used in wait(2) system call.
typedef int sys::code_type
Alias for exit code type used in wait(2) system call.
typedef basic_status< wstat_type > sys::proc_status
Alias for basic_status<wstat_type>.
typedef int sys::shm_type
Alias for shared memory ID type.
Enumerations
enum sys::wait_flags : int {
sys::wait_flags::proc_exited = WEXITED,
sys::wait_flags::proc_stopped = WSTOPPED,
sys::wait_flags::proc_continued = WCONTINUED
}
Flags used by waitid(2) system call.
enum sys::signal : signal_type {
sys::signal::hang_up = SIGHUP,
sys::signal::keyboard_interrupt = SIGINT,
sys::signal::quit = SIGQUIT,
sys::signal::illegal_instruction = SIGILL,
sys::signal::abort = SIGABRT,
sys::signal::floating_point_exception = SIGFPE,
sys::signal::kill = SIGKILL,
sys::signal::segmentation_fault = SIGSEGV,
sys::signal::broken_pipe = SIGPIPE,
sys::signal::alarm = SIGALRM,
sys::signal::terminate = SIGTERM,
sys::signal::user_defined_1 = SIGUSR1,
sys::signal::user_defined_2 = SIGUSR2,
sys::signal::child = SIGCHLD,
sys::signal::resume = SIGCONT,
sys::signal::stop = SIGSTOP,
sys::signal::terminal_stop = SIGTSTP,
sys::signal::terminal_input = SIGTTIN,
sys::signal::terminal_output = SIGTTOU,
sys::signal::bad_memory_access = SIGBUS,
sys::signal::poll = SIGPOLL,
sys::signal::profile = SIGPROF,
sys::signal::bad_argument = SIGSYS,
sys::signal::breakpoint = SIGTRAP,
sys::signal::urgent = SIGURG,
sys::signal::virtual_alarm = SIGVTALRM,
sys::signal::cpu_time_limit_exceeded = SIGXCPU,
sys::signal::file_size_limit_exceeded = SIGXFSZ,
sys::signal::coprocessor_stack_fault = SIGSTKFLT,
sys::signal::power_failure = SIGPWR,
sys::signal::terminal_window_resize = SIGWINCH
}
Process signals.
Functions
int sys::this_process::execute (char *const argv[], char *const envp[])
Execute child process with arguments argv and environment envp.
int sys::this_process::execute (const argstream &args, const argstream &env)
Execute child process with arguments args and environment env.
int sys::this_process::execute (char *const argv[])
Execute child process with arguments argv and calling process environment.
int sys::this_process::execute (const argstream &args)
Execute child process with arguments args and calling process environment.
int sys::this_process::execute_command (char *const argv[], char *const envp[])
Execute child process with arguments argv and environment envp.
int sys::this_process::execute_command (char *const argv[])
Execute child process with arguments argv and calling process environment.
int sys::this_process::execute_command (const argstream &args)
Execute child process with arguments args and calling process environment.
void sys::this_process::set_identity (uid_type uid, gid_type gid)
Set both UID and GID of the current process.
std::ostream & sys::operator<< (std::ostream &out, const signal rhs)
Output signal name.
void sys::this_process::bind_signal (signal sig, const signal_action &action)
Set signal callback function.
void sys::this_process::ignore_signal (signal sig)
Ignore specified signal.
Detailed Description
Resource management and parallel execution.
Typedef Documentation
code_type
typedef int sys::code_type
Alias for exit code type used in wait(2) system call.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 6 of file basic_status.
pid_type
typedef::pid_t sys::pid_type
Alias for pid_t;.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 11 of file identity.
proc_info
typedef basic_status<siginfo_type> sys::proc_info
Alias for basic_status<siginfo_type>.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 166 of file proc_info.
proc_status
typedef basic_status<wstat_type> sys::proc_status
Alias for basic_status<wstat_type>.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 130 of file proc_status.
shm_type
typedef int sys::shm_type
Alias for shared memory ID type.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 22 of file sharedmem.
siginfo_type
typedef ::siginfo_t sys::siginfo_type
Alias for signinfo_t;.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 17 of file proc_info.
wstat_type
typedef int sys::wstat_type
Alias for status type used in wait(2) system call.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 18 of file proc_status.
Enumeration Type Documentation
signal
enum sys::signal : signal_type strong
Process signals.
Date
2018-05-21
Author
Ivan Gankevich
See also
signal(7)
Enumerator
hang_up
Interrupt.
keyboard_interrupt
Keyboard interrupt.
quit
Keyboard quit.
illegal_instruction
Illegal processor instrucion encountered.
abort
Abort signal from abort(3).
floating_point_exception
Floating-point arithmetic exception.
kill
Forcibly terminate.
segmentation_fault
Invalid memory address was accessed.
broken_pipe
Write to a pipe(2) that is closed on the other end.
alarm
A signal from alarm(2) clock or interval timer setitimer(2).
terminate
Gracefully terminate.
user_defined_1
User-defined signal 1.
user_defined_2
User-defined signal 2.
child
Child process stopped or terminated.
resume
Resume process execution.
stop
Pause process execution.
terminal_stop
Stop signal from controlling terminal.
terminal_input
Background process tried to read from controlling terminal.
terminal_output
Background process tried to write to controlling terminal.
bad_memory_access
Memory bus error.
poll
Asyncrhonous input/output event signal.
profile
A signal from interval timer setitimer(2).
bad_argument
Bad argument to system call.
breakpoint
Breakpoint reached by the programme being debugged.
urgent
Out-of-band data arrived at a socket.
virtual_alarm
A signal from interval timer setitimer(2).
cpu_time_limit_exceeded
CPU time soft limit, which is set by setrlimit(2), exceeded.
file_size_limit_exceeded
Maximum file size limit, which is set by setrlimit(2), exceeded.
coprocessor_stack_fault
Stack fault on coprocessor (unused signal).
power_failure
Power failure.
terminal_window_resize
Controlling terminal changed its window size.
Definition at line 34 of file signal.
wait_flags
enum sys::wait_flags : int strong
Flags used by waitid(2) system call.
Date
2018-05-21
Author
Ivan Gankevich
Enumerator
proc_exited
Process exited by calling exit(2).
proc_stopped
Process execution was stopped by a signal.
proc_continued
Process execution was continued with signal::resume signal.
Definition at line 114 of file process.
Function Documentation
bind_signal()
void sys::this_process::bind_signal (signal sig, const signal_action & action) inline
Set signal callback function.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 156 of file signal.
References UNISTDX_CHECK.
Referenced by sys::this_process::ignore_signal().
execute() [1/4]
int sys::this_process::execute (char *const argv[], char *const envp[]) inline
Execute child process with arguments argv and environment envp.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable path is specified as the first argument.
The executable name is not searched in PATH.
How-tos:
Execute child process with arguments and environment (WIP)
Examples:
execute.cc.
Definition at line 28 of file execute.
References UNISTDX_CHECK.
Referenced by sys::this_process::execute().
execute() [2/4]
int sys::this_process::execute (const argstream & args, const argstream & env) inline
Execute child process with arguments args and environment env.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable path is specified as the first argument.
The executable name is not searched in PATH.
How-tos:
Execute child process with arguments and environment (WIP)
Definition at line 40 of file execute.
References sys::argstream::argv(), and sys::this_process::execute().
execute() [3/4]
int sys::this_process::execute (char *const argv[]) inline
Execute child process with arguments argv and calling process environment.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable path is specified as the first argument.
The executable name is not searched in PATH.
How-tos:
Execute child process with arguments and environment (WIP)
Definition at line 51 of file execute.
References UNISTDX_CHECK.
execute() [4/4]
int sys::this_process::execute (const argstream & args) inline
Execute child process with arguments args and calling process environment.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable path is specified as the first argument.
The executable name is not searched in PATH.
How-tos:
Execute child process with arguments and environment (WIP)
Definition at line 64 of file execute.
References sys::argstream::argv(), and sys::this_process::execute().
execute_command() [1/3]
int sys::this_process::execute_command (char *const argv[], char *const envp[]) inline
Execute child process with arguments argv and environment envp.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable is specified as the first argument argv[0].
Uses PATH environment variable to search for the executable.
How-tos:
Execute child process with arguments and environment (WIP)
Examples:
execute_command.cc.
Definition at line 82 of file execute.
References UNISTDX_CHECK.
Referenced by sys::this_process::execute_command().
execute_command() [2/3]
int sys::this_process::execute_command (char *const argv[]) inline
Execute child process with arguments argv and calling process environment.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable is specified as the first argument argv[0].
Uses PATH environment variable to search for the executable.
How-tos:
Execute child process with arguments and environment (WIP)
Definition at line 94 of file execute.
References UNISTDX_CHECK.
execute_command() [3/3]
int sys::this_process::execute_command (const argstream & args) inline
Execute child process with arguments args and calling process environment.
Date
2018-05-21
Author
Ivan Gankevich
See also
argstream
The executable is specified as the first argument argv[0].
Uses PATH environment variable to search for the executable.
How-tos:
Execute child process with arguments and environment (WIP)
Definition at line 106 of file execute.
References sys::argstream::argv(), and sys::this_process::execute_command().
ignore_signal()
void sys::this_process::ignore_signal (signal sig) inline
Ignore specified signal.
Date
2018-05-21
Author
Ivan Gankevich
By default any signal for which callback function is not set may kill the process. This routine allows to ignore specified signals.
Definition at line 171 of file signal.
References sys::this_process::bind_signal().
operator<<()
std::ostream & sys::operator<< (std::ostream & out, const signal rhs)
Output signal name.
Date
2018-05-21
Author
Ivan Gankevich
Definition at line 65 of file signal.cc.
set_identity()
void sys::this_process::set_identity (uid_type uid, gid_type gid)
Set both UID and GID of the current process.
Date
2018-05-21
Author
Ivan Gankevich
Sets GID first.
Reverts process UID and GID upon error.
Definition at line 4 of file identity.cc.
References UNISTDX_CHECK.