UNISTDX: sys::this_process Namespace Reference
sys::this_process Namespace Reference
Routines implicitly applied to the currect process.
Functions
sys::canonical_path workdir ()
Get canonical path to the working directory of the calling process.
int execute (char *const argv[], char *const envp[])
Execute child process with arguments argv and environment envp.
int execute (const argstream &args, const argstream &env)
Execute child process with arguments args and environment env.
int execute (char *const argv[])
Execute child process with arguments argv and calling process environment.
int execute (const argstream &args)
Execute child process with arguments args and calling process environment.
int execute_command (char *const argv[], char *const envp[])
Execute child process with arguments argv and environment envp.
int execute_command (char *const argv[])
Execute child process with arguments argv and calling process environment.
int execute_command (const argstream &args)
Execute child process with arguments args and calling process environment.
uid_type user () noexcept
Get real UID of the current process.
void set_user (uid_type rhs)
Change process' user.
uid_type effective_user () noexcept
Get effective UID of the current process.
gid_type group () noexcept
Get real GID of the current process.
void set_group (gid_type rhs)
Change process' group.
gid_type effective_group () noexcept
Get effective GID of the current process.
void set_identity (uid_type uid, gid_type gid)
Set both UID and GID of the current process.
pid_type id () noexcept
Get calling process ID.
pid_type parent_id () noexcept
Get calling process' parent ID.
pid_type fork ()
Fork child process preventing race conditions by locking global fork mutex (if needed).
void send (signal s)
Send signal s to the current process.
void workdir (const char *wd)
Set current process' working directory.
void set_group_id (pid_type rhs)
Set calling process group ID.
pid_type process_group_id () noexcept
Get process group ID of the calling process.
void set_process_group_id (pid_type rhs)
Set process group ID of the calling process.
void bind_signal (signal sig, const signal_action &action)
Set signal callback function.
void ignore_signal (signal sig)
Ignore specified signal.
Detailed Description
Routines implicitly applied to the currect process.
Function Documentation
effective_group()
gid_type sys::this_process::effective_group () inline noexcept
Get effective GID of the current process.
See also
getegid(2)
Definition at line 77 of file identity.
effective_user()
uid_type sys::this_process::effective_user () inline noexcept
Get effective UID of the current process.
See also
geteuid(2)
Definition at line 51 of file identity.
fork()
pid_type sys::this_process::fork () inline
Fork child process preventing race conditions by locking global fork mutex (if needed).
Exceptions
bad_call
See also
fork(2)
The mutex is not locked on systems supporting close-on-exec and non-blocking file descriptor flags.
Definition at line 63 of file process.
References UNISTDX_CHECK.
group()
gid_type sys::this_process::group () inline noexcept
Get real GID of the current process.
See also
getgid(2)
Definition at line 58 of file identity.
id()
pid_type sys::this_process::id () inline noexcept
Get calling process ID.
See also
getpid(2)
Definition at line 44 of file process.
Referenced by sys::two_way_pipe::is_owner(), sys::two_way_pipe::open(), send(), set_group_id(), and set_process_group_id().
parent_id()
pid_type sys::this_process::parent_id () inline noexcept
Get calling process' parent ID.
See also
getppid(2)
Definition at line 51 of file process.
process_group_id()
pid_type sys::this_process::process_group_id () inline noexcept
Get process group ID of the calling process.
See also
getpgrp(2)
Definition at line 19 of file process_group.
send()
void sys::this_process::send (signal s) inline
Send signal s to the current process.
Date
2018-05-21
Author
Ivan Gankevich
Exceptions
bad_call
See also
kill(2)
Definition at line 81 of file process.
References id(), sys::kill, and UNISTDX_CHECK.
set_group()
void sys::this_process::set_group (gid_type rhs) inline
Change process' group.
Exceptions
bad_call
See also
setgid(2)
Set both real and effective GID of the current process (if priviledged).
Set only effective GID of the current process (if unpriviledged).
Definition at line 68 of file identity.
References UNISTDX_CHECK.
set_group_id()
void sys::this_process::set_group_id (pid_type rhs) inline
Set calling process group ID.
Exceptions
bad_call
See also
setpgid(2)
Definition at line 103 of file process.
References id(), and UNISTDX_CHECK.
set_process_group_id()
void sys::this_process::set_process_group_id (pid_type rhs) inline
Set process group ID of the calling process.
Exceptions
bad_call
See also
setpgid(2)
Definition at line 27 of file process_group.
References id(), and UNISTDX_CHECK.
set_user()
void sys::this_process::set_user (uid_type rhs) inline
Change process' user.
Exceptions
bad_call
See also
setuid(2)
Set both real and effective UID of the current process (if priviledged).
Set only effective UID of the current process (if unpriviledged).
Definition at line 42 of file identity.
References UNISTDX_CHECK.
user()
uid_type sys::this_process::user () inline noexcept
Get real UID of the current process.
See also
getuid(2)
Definition at line 32 of file identity.
workdir()
void sys::this_process::workdir (const char * wd) inline
Set current process' working directory.
Date
2018-05-21
Author
Ivan Gankevich
Exceptions
bad_call
See also
chdir(2)
Definition at line 93 of file process.
References UNISTDX_CHECK.