UNISTDX: sys::poll_event Struct Reference
sys::poll_event Struct Reference
System abstractions » WrappersSystem abstractions » | IO
File descriptor event wrapper for poll(2) system call.
Public Types
enum event_type : legacy_event {
In = POLLIN,
Out = POLLOUT,
Hup = POLLHUP | UNISTDX_POLLRDHUP,
Err = POLLERR | POLLNVAL,
Inout = POLLIN | POLLOUT,
Def = UNISTDX_POLLRDHUP
}
Input/output events.
Public Member Functions
constexpr poll_event (fd_type f=-1, legacy_event ev=0, legacy_event rev=0) noexcept
poll_event & operator= (const poll_event &) noexcept=default
Assignment.
constexpr legacy_event revents () const noexcept
Get recorded event mask.
constexpr legacy_event events () const noexcept
Get event mask.
void disable () noexcept
Disable polling by setting file descriptor to -1.
constexpr fd_type fd () const noexcept
Get file descriptor.
constexpr bool bad_fd () const noexcept
Returns true, if file descriptor is invalid.
constexpr bool in () const noexcept
Returns true, if input event occurred.
constexpr bool out () const noexcept
Returns true, if output event occurred.
constexpr bool hup () const noexcept
constexpr bool err () const noexcept
Returns true, if an error occurred.
constexpr bool bad () const noexcept
Returns true, if an error or hang up occurred.
void setev (event_type rhs) noexcept
Set events rhs in event mask.
void unsetev (event_type rhs) noexcept
Unset events rhs in event mask.
void setrev (event_type rhs) noexcept
Set events rhs in recorded event mask.
void unsetrev (event_type rhs) noexcept
Unset events rhs in recorded event mask.
void setall (event_type rhs) noexcept
Set events rhs in event mask and recorded event mask.
ssize_t probe () const noexcept
Probe file descriptor by peeking a byte from it.
constexpr bool operator== (const poll_event &rhs) const noexcept
Returns true, if events have the same file descriptor.
constexpr bool operator!= (const poll_event &rhs) const noexcept
Returns true, if events have different file descriptors.
constexpr bool operator< (const poll_event &rhs) const noexcept
Compares file descriptors.
constexpr operator bool () const noexcept
constexpr bool operator! () const noexcept
Public Attributes
decltype(basic_event::events) typedef legacy_event
Event mask type.
Friends
constexpr legacy_event operator| (event_type lhs, event_type rhs) noexcept
Bit-wise OR.
constexpr legacy_event operator| (legacy_event lhs, event_type rhs) noexcept
Bit-wise OR.
constexpr legacy_event operator| (event_type lhs, legacy_event rhs) noexcept
Bit-wise OR.
constexpr legacy_event operator & (event_type lhs, event_type rhs) noexcept
Bit-wise AND.
constexpr legacy_event operator & (legacy_event lhs, event_type rhs) noexcept
Bit-wise AND.
constexpr legacy_event operator & (event_type lhs, legacy_event rhs) noexcept
Bit-wise AND.
std::ostream & operator<< (std::ostream &out, const poll_event &rhs)
Output file descriptor and event mask for debugging.
Detailed Description
File descriptor event wrapper for poll(2) system call.
Date
2018-05-23
Author
Ivan Gankevich
Definition at line 22 of file poll_event.
Constructor & Destructor Documentation
poll_event()
constexpr sys::poll_event::poll_event (fd_type f = -1, legacy_event ev = 0, legacy_event rev = 0) inline explicit noexcept
Construct object from file descriptor f, event mask ev and recorded events rev.
Definition at line 80 of file poll_event.
Member Function Documentation
bad()
constexpr bool sys::poll_event::bad () const inline noexcept
Returns true, if an error or hang up occurred.
Definition at line 148 of file poll_event.
References revents().
Referenced by operator bool().
bad_fd()
constexpr bool sys::poll_event::bad_fd () const inline noexcept
Returns true, if file descriptor is invalid.
Definition at line 118 of file poll_event.
References fd().
Referenced by operator bool().
disable()
void sys::poll_event::disable () inline noexcept
Disable polling by setting file descriptor to -1.
Definition at line 106 of file poll_event.
err()
constexpr bool sys::poll_event::err () const inline noexcept
Returns true, if an error occurred.
Definition at line 142 of file poll_event.
References revents().
Referenced by sys::operator<<().
events()
constexpr legacy_event sys::poll_event::events () const inline noexcept
Get event mask.
Definition at line 100 of file poll_event.
Referenced by sys::operator<<().
fd()
constexpr fd_type sys::poll_event::fd () const inline noexcept
Get file descriptor.
Definition at line 112 of file poll_event.
Referenced by bad_fd(), operator!=(), operator<(), sys::operator<<(), operator==(), and probe().
hup()
constexpr bool sys::poll_event::hup () const inline noexcept
Returns true, if hang up event occurred (the other end of the channel was closed).
Definition at line 136 of file poll_event.
References revents().
Referenced by sys::operator<<().
in()
constexpr bool sys::poll_event::in () const inline noexcept
Returns true, if input event occurred.
Definition at line 124 of file poll_event.
References revents().
Referenced by sys::operator<<().
operator bool()
constexpr sys::poll_event::operator bool () const inline explicit noexcept
Returns true, if file descriptor is valid and no bad events occurred.
Definition at line 212 of file poll_event.
References bad(), and bad_fd().
operator!()
constexpr bool sys::poll_event::operator! () const inline noexcept
Returns true, if either file descriptor is invalid, or a bad event occurred.
Definition at line 218 of file poll_event.
operator!=()
constexpr bool sys::poll_event::operator!= (const poll_event & rhs) const inline noexcept
Returns true, if events have different file descriptors.
Definition at line 197 of file poll_event.
References fd().
operator<()
constexpr bool sys::poll_event::operator< (const poll_event & rhs) const inline noexcept
Compares file descriptors.
Definition at line 203 of file poll_event.
References fd().
operator==()
constexpr bool sys::poll_event::operator== (const poll_event & rhs) const inline noexcept
Returns true, if events have the same file descriptor.
Definition at line 191 of file poll_event.
References fd().
out()
constexpr bool sys::poll_event::out () const inline noexcept
Returns true, if output event occurred.
Definition at line 130 of file poll_event.
References revents().
Referenced by sys::operator<<().
probe()
ssize_t sys::poll_event::probe () const inline noexcept
Probe file descriptor by peeking a byte from it.
Definition at line 184 of file poll_event.
References fd().
setev()
void sys::poll_event::setev (event_type rhs) inline noexcept
Set events rhs in event mask.
Definition at line 154 of file poll_event.
Referenced by setall().
unsetev()
void sys::poll_event::unsetev (event_type rhs) inline noexcept
Unset events rhs in event mask.
Definition at line 160 of file poll_event.