UNISTDX: sys::basic_status< wstat_type > Struct Template Reference
sys::basic_status< wstat_type > Struct Template Reference
System abstractions » ProcessesSystem abstractions » | Wrappers
A basic_status object that tells how the process was terminated.
Public Member Functions
constexpr basic_status (wstat_type rhs) noexcept
Construct process status from raw wait status.
constexpr basic_status (const basic_status &) noexcept=default
Copy-constructor.
constexpr bool exited () const noexcept
Process has exited.
constexpr bool killed () const noexcept
Process has beed killed.
constexpr bool stopped () const noexcept
Process has beed stopped.
constexpr bool core_dumped () const noexcept
Process has dumped the core.
constexpr bool trapped () const noexcept
Always returns false for compatibility with proc_info.
constexpr bool continued () const noexcept
Process received a signal to continue execution after a stop.
constexpr code_type exit_code () const noexcept
Get process exit code.
constexpr signal term_signal () const noexcept
Get process termination signal.
constexpr signal stop_signal () const noexcept
Get process stop signal.
constexpr const char * status_string () const noexcept
Get process status string.
Detailed Description
template<>
struct sys::basic_status< wstat_type >
A basic_status object that tells how the process was terminated.
Date
2018-05-21
Author
Ivan Gankevich
Wraps wstat_type.
Definition at line 39 of file proc_status.
Member Function Documentation
continued()
constexpr bool sys::basic_status< wstat_type >::continued () const inline noexcept
Process received a signal to continue execution after a stop.
Definition at line 94 of file proc_status.
Referenced by sys::operator<<().
core_dumped()
constexpr bool sys::basic_status< wstat_type >::core_dumped () const inline noexcept
Process has dumped the core.
Definition at line 78 of file proc_status.
exit_code()
constexpr code_type sys::basic_status< wstat_type >::exit_code () const inline noexcept
Get process exit code.
Definition at line 100 of file proc_status.
Referenced by sys::operator<<(), and sys::process_group::wait().
exited()
constexpr bool sys::basic_status< wstat_type >::exited () const inline noexcept
Process has exited.
Definition at line 60 of file proc_status.
Referenced by sys::operator<<().
killed()
constexpr bool sys::basic_status< wstat_type >::killed () const inline noexcept
Process has beed killed.
Definition at line 66 of file proc_status.
Referenced by sys::operator<<().
stop_signal()
constexpr signal sys::basic_status< wstat_type >::stop_signal () const inline noexcept
Get process stop signal.
Definition at line 112 of file proc_status.
Referenced by sys::operator<<().
stopped()
constexpr bool sys::basic_status< wstat_type >::stopped () const inline noexcept
Process has beed stopped.
Definition at line 72 of file proc_status.
Referenced by sys::operator<<().
term_signal()
constexpr signal sys::basic_status< wstat_type >::term_signal () const inline noexcept
Get process termination signal.
Definition at line 106 of file proc_status.
Referenced by sys::operator<<(), and sys::process_group::wait().