UNISTDX: sys::endpoint Union Reference
sys::endpoint Union Reference
System abstractions » WrappersSystem abstractions » | Network
Socket address wrapper.
Public Member Functions
constexpr endpoint (const endpoint &rhs) noexcept
Copy-constructor.
endpoint (const char *host, const port_type port)
Construct endpoint with host and port.
constexpr endpoint (const ipv4_addr h, const port_type p) noexcept
Construct endpoint with IPv4 address h and port p.
constexpr endpoint (const ipv6_addr &h, const port_type p) noexcept
Construct endpoint with IPv6 address h and port p.
constexpr endpoint (const sockinet4_type &rhs) noexcept
Construct endpoint from sockaddr_in system type.
constexpr endpoint (const sockinet6_type &rhs) noexcept
Construct endpoint from sockaddr_in6 system type.
constexpr endpoint (const sa_type &rhs) noexcept
Construct endpoint from sockaddr system type.
endpoint (const char *unix_socket_path) noexcept
Construct endpoint from unix socket path.
endpoint (int groups)
Construct endpoint by specifying netlink groups.
constexpr endpoint (const endpoint &rhs, const port_type newport) noexcept
Construct endpoint from another one and a new port.
bool operator< (const endpoint &rhs) const noexcept
Compare endpoints taking into account particular address family.
bool operator== (const endpoint &rhs) const noexcept
Compare endpoints taking into account particular address family.
bool operator>= (const endpoint &rhs) const noexcept
Compare endpoints taking into account particular address family.
bool operator!= (const endpoint &rhs) const noexcept
Compare endpoints taking into account particular address family.
constexpr operator bool () const noexcept
Returns true, if endpoint has valid address and family.
constexpr bool operator! () const noexcept
Returns true, if endpoint has either invalid address or invalid family.
constexpr port_type port () const noexcept
Get endpoint port.
constexpr family_type family () const noexcept
Get endpoint address family.
constexpr sa_family_type sa_family () const noexcept
Get endpoint address family.
void reset () noexcept
Reset endpoint value to nought.
constexpr ipv4_addr addr4 () const noexcept
Get IPv4 address.
constexpr port_type port4 () const
Get IPv4 port.
constexpr ipv6_addr addr6 () const
Get IPv6 address.
constexpr port_type port6 () const
Get IPv6 port.
sa_type * sockaddr () noexcept
Get socket address suitable for passing as an argument to system calls.
sa_type * sockaddr () const noexcept
Get socket address suitable for passing as an argument to system calls.
socklen_type sockaddrlen () const noexcept
Friends
struct std::hash< sys::endpoint >
std::ostream & operator<< (std::ostream &out, const endpoint &rhs)
Print textual representation of the endpoint.
std::istream & operator>> (std::istream &in, endpoint &rhs)
Parse textual representation of the endpoint.
pstream & operator<< (pstream &out, const endpoint &rhs)
Put endpoint in binary form.
pstream & operator>> (pstream &in, endpoint &rhs)
Get endpoint in binary form.
Detailed Description
Socket address wrapper.
Date
2018-05-23
Author
Ivan Gankevich
This class wraps all socket address types. Socket address is retrieved with sockaddr method and its length with sockaddrlen method.
This is variant class, type of which is encoded in address family.
Definition at line 96 of file endpoint.
Constructor & Destructor Documentation
endpoint()
sys::endpoint::endpoint (const char * host, const port_type port) inline
Construct endpoint with host and port.
Date
2018-05-23
Author
Ivan Gankevich
Host name resolution is not performed.
Parameter host is text representation of an IP-address.
Definition at line 126 of file endpoint.
References port().
Member Function Documentation
operator!=()
bool sys::endpoint::operator!= (const endpoint & rhs) const inline noexcept
Compare endpoints taking into account particular address family.
Definition at line 202 of file endpoint.
References operator==().
operator==()
bool sys::endpoint::operator== (const endpoint & rhs) const noexcept
Compare endpoints taking into account particular address family.
Definition at line 223 of file endpoint.cc.
References sys::inet, sys::inet6, sys::netlink, and sys::unix.
Referenced by operator!=().
operator>=()
bool sys::endpoint::operator>= (const endpoint & rhs) const inline noexcept
Compare endpoints taking into account particular address family.
Definition at line 196 of file endpoint.
References operator<().
sockaddrlen()
sys::socklen_type sys::endpoint::sockaddrlen () const noexcept
Get socket address length, suitable for passing as an argument to system calls.
Definition at line 168 of file endpoint.cc.
References sys::inet, sys::inet6, sys::netlink, and sys::unix.
Referenced by sys::socket::bind(), and sys::socket::connect().