var searchData=
[
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['validate',['validate',['../classsys_1_1fildes.html#a41ecd7c26ef092591e4ce393f5aef4e1',1,'sys::fildes::validate()'],['../classsys_1_1two__way__pipe.html#a8819041b746974df01fe84b4c097f95d',1,'sys::two_way_pipe::validate()']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['../unionsys_1_1bytes.html#af0bf6c51ed812252d4ab6b1992c9b0eb',1,'sys::bytes::value() const noexcept'],['../unionsys_1_1bytes.html#abf054f31958a9207cbef19a1dcc56fa4',1,'sys::bytes::value() noexcept']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5ftype',['value_type',['../classsys_1_1byte__buffer.html#a9729fd836064b480632ff6c75b0d83bb',1,'sys::byte_buffer::value_type()'],['../classsys_1_1event__poller.html#a77b4ba90e7897d215dab08ca0d92109d',1,'sys::event_poller::value_type()'],['../classsys_1_1shared__mem.html#a0eb4a3234b829608fb5e95643b811a43',1,'sys::shared_mem::value_type()'],['../structsys_1_1container__traits.html#a8085166665c9f358ecf698dc924a26f4',1,'sys::container_traits::value_type()'],['../classsys_1_1field__iterator.html#a190ff9b4aa399689f7b45a8dca5c7ca1',1,'sys::field_iterator::value_type()'],['../classsys_1_1iterator__pair.html#a50fcd37c7e97d6ffe0c0786c79ef2fad',1,'sys::iterator_pair::value_type()'],['../unionsys_1_1bytes.html#ab81ece3bbc46a968c1ae9f9909752045',1,'sys::bytes::value_type()'],['../classsys_1_1ifaddrs.html#a790d1eae7d6141bdc8c04aec573ef68a',1,'sys::ifaddrs::value_type()'],['../classsys_1_1netlink__container.html#a4533eec390c4bd00f20b3b9ebfc7bec4',1,'sys::netlink_container::value_type()'],['../classsys_1_1cache.html#a38924cb1078788229c0da7dbb2c9d4b7',1,'sys::cache::value_type()']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20char_5ftype_20_2a_3e',['vector&lt; char_type *&gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20epoll_5fevent_20_3e',['vector&lt; epoll_event &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_20_3e',['vector&lt; std::vector &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20sys_3a_3aprocess_20_3e',['vector&lt; sys::process &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_5ftraits',['vector_traits',['../structsys_1_1vector__traits.html',1,'sys']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['virtual_5falarm',['virtual_alarm',['../group__ipc.html#ggabbd54203abe643c317a3d3acafcc4cc4ac3c6681439c909c1d4d4fbd896113b65',1,'sys']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
