var searchData=
[
  ['scoped_5fallocator_5fadaptor',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seconds',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream::sentry']]],
  ['set',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['sha1',['sha1',['../classsys_1_1sha1.html',1,'sys']]],
  ['shared_5ffuture',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fmem',['shared_mem',['../classsys_1_1shared__mem.html',1,'sys']]],
  ['shared_5fmem_3c_20char_5ftype_20_3e',['shared_mem&lt; char_type &gt;',['../classsys_1_1shared__mem.html',1,'sys']]],
  ['shared_5fptr',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['sharedmem_5fstat',['sharedmem_stat',['../classsys_1_1sharedmem__stat.html',1,'sys']]],
  ['shuffle_5forder_5fengine',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['signal_5faction',['signal_action',['../classsys_1_1signal__action.html',1,'sys']]],
  ['signal_5fguard',['signal_guard',['../classsys_1_1signal__guard.html',1,'sys']]],
  ['sigset_5ftype',['sigset_type',['../classsys_1_1sigset__type.html',1,'sys']]],
  ['simple_5flock',['simple_lock',['../classsys_1_1simple__lock.html',1,'sys']]],
  ['size_5ft',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['smatch',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['socket',['socket',['../classsys_1_1socket.html',1,'sys']]],
  ['spin_5fmutex',['spin_mutex',['../classsys_1_1spin__mutex.html',1,'sys']]],
  ['sregex_5fiterator',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::state_type']]],
  ['steady_5fclock',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['streambuf',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streambuf_5ftraits',['streambuf_traits',['../structsys_1_1streambuf__traits.html',1,'sys']]],
  ['streambuf_5ftraits_3c_20fd_5ftype_20_3e',['streambuf_traits&lt; fd_type &gt;',['../structsys_1_1streambuf__traits_3_01fd__type_01_4.html',1,'sys']]],
  ['streambuf_5ftraits_3c_20fildes_20_3e',['streambuf_traits&lt; fildes &gt;',['../structsys_1_1streambuf__traits_3_01fildes_01_4.html',1,'sys']]],
  ['streambuf_5ftraits_3c_20fildes_5fpair_20_3e',['streambuf_traits&lt; fildes_pair &gt;',['../structsys_1_1streambuf__traits_3_01fildes__pair_01_4.html',1,'sys']]],
  ['streambuf_5ftraits_3c_20socket_20_3e',['streambuf_traits&lt; socket &gt;',['../structsys_1_1streambuf__traits_3_01socket_01_4.html',1,'sys']]],
  ['streamoff',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamptr',['streamptr',['../structsys_1_1streamptr.html',1,'sys']]],
  ['streamsize',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::string_type']]],
  ['stringbuf',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strstream',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subnet_5fiterator',['subnet_iterator',['../classsys_1_1subnet__iterator.html',1,'sys']]],
  ['subtract_5fwith_5fcarry_5fengine',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['system_5fclock',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]],
  ['sysv_5fsemaphore',['sysv_semaphore',['../classsys_1_1sysv__semaphore.html',1,'sys']]]
];
