#!/bin/sh


set -e
outdir="$MESON_BUILD_ROOT/man/man3"
mkdir -p "$outdir"
for i in $MESON_BUILD_ROOT/xml/namespace*.xml
do
	xsltproc "$MESON_SOURCE_ROOT/doc/get-ids.xml" "$i" |
	while read name namespace file
	do
		if test -n "$name" -a -n "$namespace" -a -n "$file"
		then
			echo $name $namespace $file $i
			date=$(git log -1 --format="%ad" --date=short -- "$MESON_SOURCE_ROOT/$file")
			xsltproc \
				--output "$outdir/$namespace::$name.3" \
				--stringparam "memberName" "$name" \
				--stringparam "lastChanged" "$date" \
				"$MESON_SOURCE_ROOT/doc/man.xml" "$i"
		fi
	done
done
